# Table A7: leave-one-choice-out inputs; run from Code.
# 17 training individual choices; one held-out choice per member; 18 group choices.
# All non-own same-wave donors; undefined donor distances receive 0.5.
# LOCO_FOLDS defaults to 18; LOCO_CORES defaults to 4. Fold-one runs resume at 18.
# Estimates and diagnostics are generated by the final section of 08_Tables_Appendix.do.

build_leave_one_choice_out_inputs <- function(
    code_dir = getwd(), folds = as.integer(Sys.getenv("LOCO_FOLDS", "18")),
    cores = as.integer(Sys.getenv("LOCO_CORES", "4")),
    output_dir = Sys.getenv("LOCO_OUTPUT_DIR", file.path(code_dir, "results/tests/disjoint_choice"))) {
  code_dir <- normalizePath(code_dir, mustWork = TRUE)
  stopifnot(length(folds) == 1L, folds %in% 1:18,
            length(cores) == 1L, is.finite(cores), cores >= 1L)
  source(file.path(code_dir, "programs/calculate_rp_indices.R"), local = TRUE)
  source(file.path(code_dir, "programs/build_placebo_donor_matrices.R"), local = TRUE)
  seed <- 20260812L
  plain <- function(x) trimws(as.character(x))
  pairs <- as.data.frame(haven::read_dta(file.path(code_dir, "data/panel_final.dta")))
  pairs <- pairs[, c("group_id", "id_mover_base", "id_nonmover_base", "id_mover_end", "id_nonmover_end")]
  pairs[] <- lapply(pairs, plain)
  pairs <- pairs[order(pairs$group_id), ]
  rownames(pairs) <- NULL
  stopifnot(nrow(pairs) > 1L, !anyNA(pairs), !anyDuplicated(pairs$group_id))
  base <- rp_load_wave(file.path(code_dir, "data/base_raw.dta")); base$post <- 0L
  end <- rp_load_wave(file.path(code_dir, "data/end_raw.dta")); end$post <- 1L
  raw <- rbind(base, end)
  raw <- raw[raw$group_id %in% pairs$group_id, ]
  individual <- split(raw[raw$round_number <= 18L, ], paste(raw$id[raw$round_number <= 18L], raw$post[raw$round_number <= 18L], sep = "|"))
  collective <- raw[raw$round_number >= 19L & raw$mover == 1L, ]
  collective <- split(collective, paste(collective$group_id, collective$post, sep = "|"))
  blocks <- list()
  for (wave in c("base", "end")) {
    post <- as.integer(wave == "end")
    for (k in seq_len(nrow(pairs))) {
      id1 <- pairs[[paste0("id_mover_", wave)]][k]
      id2 <- pairs[[paste0("id_nonmover_", wave)]][k]
      choices <- list(one = individual[[paste(id1, post, sep = "|")]],
                      two = individual[[paste(id2, post, sep = "|")]],
                      group = collective[[paste(pairs$group_id[k], post, sep = "|")]])
      choices <- lapply(choices, function(d) d[order(d$round_number), ])
      stopifnot(all(vapply(choices, nrow, integer(1)) == 18L), id1 != id2)
      blocks[[length(blocks) + 1L]] <- c(list(group_id = pairs$group_id[k], post = post,
                                            wave = wave, id1 = id1, id2 = id2), choices)
    }
  }
  # One independently randomized permutation for each student-wave, fixed across folds.
  set.seed(seed)
  assignment <- do.call(rbind, lapply(sort(names(individual)), function(key) {
    d <- individual[[key]]
    data.frame(id = plain(d$id[1]), post = d$post[1], fold = 1:18,
               heldout_round = sample.int(18L, 18L), stringsAsFactors = FALSE)
  }))
  permutation <- split(assignment$heldout_round, paste(assignment$id, assignment$post, sep = "|"))
  stopifnot(all(vapply(permutation, function(x) identical(sort(x), 1:18), logical(1))))
  identity_files <- file.path(code_dir, c("data/base_raw.dta", "data/end_raw.dta",
    "programs/calculate_indices_disjoint.R", "programs/calculate_rp_indices.R",
    "programs/build_placebo_donor_matrices.R", "programs/rp_donor_costs.cpp"))
  manifest <- list(version = 3L, design = "17/1 individual; 18 group", seed = seed,
                   roster = pairs, hashes = unname(tools::md5sum(identity_files)))
  manifest_path <- file.path(output_dir, "loco_config.rds")
  index_dir <- file.path(output_dir, "indices")
  if (file.exists(manifest_path)) {
    if (!identical(readRDS(manifest_path), manifest)) stop("Hold-out inputs/code changed; use a new LOCO_OUTPUT_DIR.")
  } else {
    cached <- list.files(output_dir, recursive = TRUE)
    if (any(basename(cached) != "README.md")) stop("Archive old split-choice outputs before using this directory.")
    dir.create(index_dir, recursive = TRUE, showWarnings = FALSE)
    saveRDS(manifest, manifest_path)
    write.csv(assignment, file.path(output_dir, "fold_assignments.csv"), row.names = FALSE)
  }
  distance <- function(one, two, group) {
    cost <- function(i) rp_cost_ccei(rp_expenditure(rbind(i, group)),
                                    c(rep("I", nrow(i)), rep("G", nrow(group))))
    rp_index(cost(one), cost(two), cost(rbind(one, two)))
  }
  shares <- function(d) c(corner = mean(d$coord_x == 0 | d$coord_y == 0),
                          mid = mean(d$coord_x == d$coord_y))
  for (fold in seq_len(folds)) {
    path <- file.path(index_dir, sprintf("fold_%02d.dta", fold))
    if (file.exists(path)) {
      saved <- as.data.frame(haven::read_dta(path))
      stopifnot(nrow(saved) == 4L * nrow(pairs), !anyDuplicated(saved[c("id", "post")]), all(saved$fold == fold))
      message("[resume] ", basename(path)); next
    }
    fold_pairs <- pairs
    fold_raw <- list(base = list(), end = list())
    member_rows <- vector("list", length(blocks))
    for (k in seq_along(blocks)) {
      b <- blocks[[k]]
      rows <- c(permutation[[paste(b$id1, b$post, sep = "|")]][fold],
                permutation[[paste(b$id2, b$post, sep = "|")]][fold])
      heldout <- list(one = b$one[rows[1], ], two = b$two[rows[2], ], group = b$group)
      training <- list(one = b$one[-rows[1], ], two = b$two[-rows[2], ])
      stopifnot(nrow(training$one) == 17L, nrow(training$two) == 17L,
                !rows[1] %in% training$one$round_number, !rows[2] %in% training$two$round_number)
      I1 <- distance(heldout$one, heldout$two, heldout$group)
      score1 <- 1 - rp_cost_ccei(rp_expenditure(training$one))
      score2 <- 1 - rp_cost_ccei(rp_expenditure(training$two))
      c1 <- shares(training$one); c2 <- shares(training$two)
      member_rows[[k]] <- data.frame(group_id = b$group_id, post = b$post,
        id = c(b$id1, b$id2), partner_id = c(b$id2, b$id1),
        ccei_train = c(score1, score2), partner_ccei_train = c(score2, score1),
        I_holdout = c(I1, 1-I1), heldout_round = rows,
        corner_share_train = c(c1["corner"], c2["corner"]),
        corner_diff_train = c(c1["corner"]-c2["corner"], c2["corner"]-c1["corner"]),
        mid_share_train = c(c1["mid"], c2["mid"]),
        mid_diff_train = c(c1["mid"]-c2["mid"], c2["mid"]-c1["mid"]))
      row <- match(b$group_id, fold_pairs$group_id)
      fold_pairs[row, paste0("Ihat_1g_", b$wave)] <- I1
      fold_pairs[row, paste0("Ihat_2g_", b$wave)] <- 1-I1
      fold_raw[[b$wave]][[length(fold_raw[[b$wave]])+1L]] <- do.call(rbind, heldout)
    }
    d <- do.call(rbind, member_rows)
    benchmark <- build_placebo_donor_matrix("ccei", code_dir, fold_pairs,
      do.call(rbind, fold_raw$base), do.call(rbind, fold_raw$end),
      output_dir = file.path(output_dir, "benchmarks", sprintf("fold_%02d", fold)),
      chunk_size = 32L, cores = cores, choices_per_member = 1L, group_choices = 18L,
      save_donor_matrix = FALSE)
    matched <- match(paste(d$id, d$post), paste(benchmark$id, benchmark$post))
    stopifnot(!anyNA(matched), all(benchmark$n_all == nrow(pairs)-1L),
              all(abs(d$I_holdout-benchmark$I_actual[matched]) < 1e-10 | is.na(d$I_holdout)))
    d$M_holdout <- benchmark$M_all_imp[matched]
    d$n_donors <- benchmark$n_all[matched]
    d$undefined_donor_fraction <- benchmark$degfrac_all[matched]
    d$fold <- fold
    stopifnot(nrow(d) == 4L*nrow(pairs), !anyDuplicated(d[c("id", "post")]))
    temporary <- paste0(path, ".tmp")
    haven::write_dta(d, temporary, version = 14)
    if (!file.rename(temporary, path)) stop("Could not save hold-out inputs: ", path)
    message(sprintf("[saved] fold %d/%d", fold, folds))
  }
  haven::write_dta(data.frame(version = 3L, folds = folds, planned_folds = 18L,
    n_pairs = nrow(pairs), seed = seed, training_choices = 17L, heldout_choices = 1L, group_choices = 18L),
    file.path(output_dir, "run_config.dta"), version = 14)
  # Diagnostics retain full-data rationality only for validation and sample comparisons.
  full <- as.data.frame(haven::read_dta(file.path(code_dir, "data/panel_individual.dta")))
  full$id <- plain(full$id)
  full_key <- paste(full$id, full$post)
  balanced <- ave(!is.na(full$Ihat_ig), full$id, FUN = sum) == 2
  diagnostics <- selections <- distributions <- list()
  for (fold in seq_len(folds)) {
    d <- as.data.frame(haven::read_dta(file.path(index_dir, sprintf("fold_%02d.dta", fold))))
    rows <- match(paste(d$id, d$post), full_key)
    stopifnot(!anyNA(rows))
    d$full_ccei <- full$ccei_i[rows]
    d$full_high <- full$HighCCEI_both_high[rows]
    d$balanced_full <- balanced[rows]
    d$valid_both <- ave(!is.na(d$I_holdout), d$id, FUN = sum) == 2
    d$retained <- d$balanced_full & d$valid_both
    d$delta_ccei <- d$ccei_train-d$full_ccei
    stopifnot(all(d$delta_ccei >= -1e-7), all(is.finite(d$M_holdout)))
    for (post in 0:1) {
      wave <- d[d$post == post, ]
      delta <- wave$delta_ccei
      diagnostics[[length(diagnostics)+1L]] <- data.frame(fold = fold, post = post,
        n = nrow(wave), mean_ccei_change = mean(delta), sd_ccei_change = sd(delta),
        median_ccei_change = median(delta), max_ccei_change = max(delta),
        changed_fraction = mean(abs(delta)>1e-7),
        higher_agreement = mean((wave$ccei_train>=wave$partner_ccei_train)==wave$full_high),
        training_tie_fraction = mean(wave$ccei_train==wave$partner_ccei_train),
        full_tie_fraction = mean(full$ccei_i[rows][d$post==post]==full$ccei_j[rows][d$post==post]),
        undefined_distance_n = sum(is.na(wave$I_holdout)),
        undefined_distance_fraction = mean(is.na(wave$I_holdout)),
        regression_n = sum(wave$retained),
        mean_undefined_donor_fraction = mean(wave$undefined_donor_fraction))
    }
    eligible <- d[d$balanced_full, ]
    for (status in c(FALSE, TRUE)) {
      selected <- eligible[eligible$retained == status, ]
      selections[[length(selections)+1L]] <- data.frame(fold = fold, retained = status,
        n = nrow(selected), mean_full_ccei = mean(selected$full_ccei),
        sd_full_ccei = sd(selected$full_ccei), mean_training_ccei = mean(selected$ccei_train),
        full_high_fraction = mean(selected$full_high), full_rational_fraction = mean(selected$full_ccei>=1-1e-9))
    }
    for (sample in c("all", "regression")) for (name in c("I_holdout", "M_holdout")) {
      values <- d[[name]][if (sample == "all") rep(TRUE,nrow(d)) else d$retained]
      values <- values[!is.na(values)]
      distributions[[length(distributions)+1L]] <- data.frame(fold = fold, sample = sample, measure = name,
        n = length(values), mean = mean(values), sd = sd(values), minimum = min(values),
        p10 = unname(quantile(values,.1)), median = median(values), p90 = unname(quantile(values,.9)),
        maximum = max(values), zero_fraction = mean(values<=1e-9),
        half_fraction = mean(abs(values-.5)<=1e-9), one_fraction = mean(values>=1-1e-9))
    }
  }
  write.csv(do.call(rbind, diagnostics), file.path(output_dir, "diagnostics_by_fold_wave.csv"), row.names = FALSE)
  write.csv(do.call(rbind, selections), file.path(output_dir, "sample_selection.csv"), row.names = FALSE)
  write.csv(do.call(rbind, distributions), file.path(output_dir, "distance_distributions.csv"), row.names = FALSE)
  message("Completed hold-out inputs. Run the Table A7 section of 08_Tables_Appendix.do.")
}
if (sys.nframe() == 0L) build_leave_one_choice_out_inputs()
