"""Export the chosen review results to separate manuscript assets (run from any directory)."""
import shutil
from pathlib import Path

root = Path(__file__).resolve().parents[2]
out = root / 'Code/IminusM_review/outputs'
tables = root / 'Overleaf/tables_2025'
figures = root / 'Overleaf/figures_2025'

# Main and migrated appendix tables are generated by 06/08, not the review.
canonical_tables = (
    'table_ccei_summary_IminusM.tex',
    'table_attrition_balance.tex',
    'table_bargainingCCEI_M.tex',
    'table_bargainingCCEI_buffers_M.tex',
    'table_correlation_IminusM.tex',
    'table_bargainingCCEI_mover_M.tex',
    'table_individual_ccei_change.tex',
    'table_bargaining_alternatives_M.tex',
    'table_bargainingCCEI_bothlow_M.tex',
)
for file in (out/'adopted').glob('*.tex'):
    if file.name not in canonical_tables:
        shutil.copyfile(file, tables/file.name)
for name in canonical_tables:
    shutil.copyfile(root / 'Code/results/tables' / name, tables/name)
for name in (
    'ccei_IminusM_by_higher_ccei_bar.png',
    'ccei_IminusM_by_higher_ccei_cdf.png',
    'figure4_placebo_coefficients.png',
    'figure4_placebo_col2.pdf',
    'figure4_placebo_col3.pdf',
    'hist_IminusM_ig.png',
    'figure_A7/table3_col2.pdf',
    'figure_A7/table3_col3.pdf',
    'figure_A7/table3_col5.pdf',
    'figure_A7/table3_col6.pdf',
    'figure_A7/legend.pdf',
    'figure4_placebo_col5.pdf',
    'figure4_placebo_col6.pdf',
    'figure_A8_placebo_coefficients.png',
):
    (figures/name).parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(root / 'Code/results/figures' / name, figures/name)

# Table A5 is fitted and exported directly by 08 using the full donor benchmarks.

# Tables A2/A4 are copied from 08's canonical exports, preserving draft labels.
print('Exported adopted tables and canonical Figures 3, 4, A6, A7, and A8 in draft order.')
