********************************************************************************
* 08_Tables_Appendix.do: Appendix tables and Shapley decomposition inputs
* Last updated: 2026-10-10
* Locked draft order: Tables A1 (buffers), A2 (I-M correlations), A3 (mover),
* A4 (individual CCEI changes), A5 (alternative measures), A6 (strictly higher CCEI),
* followed by supplementary analyses.
* Run from Code. The Section 6.3 table export reads table5_coefficients.csv
* and table5_diagnostics.csv from results/new_indices/collective_rationality_summary,
* generated by 11_collective_quality.do. It writes collective_ccei_ceiv_categories.tex
* to results/tables and copies it to ../Overleaf/tables_2025.
* The choice-buffer section rebuilds exact, 2.5-point, and 5-point shares from raw
* choices and controls for M from IminusM_review/outputs/data/ccei_ra_candidate_analysis.dta.
* It writes table_bargainingCCEI_buffers_M.tex to results/tables and Overleaf,
* with its estimation log in Logs/08_choice_buffers.log.
* Table A5 uses full HM/MaxMPI benchmarks from results/benchmarks and the retained
* full RA benchmark. It exports table_bargaining_alternatives_M.tex/.csv;
* its log is Logs/08_alternative_full.log.
* Hold-out validation reads 17/1 inputs from programs/calculate_indices_disjoint.R
* and estimates the six Table 3 specifications directly in this dofile. It writes
* results/tables/table_leave_one_choice_out.tex after all 18 folds.
* The Table 3 extensions export table_bargainingCCEI_{mover,bothlow}_M.tex
* from the validated analysis panel retained with the CCEI benchmark.
* Mover log: Logs/08_table3_extensions.log; ties-low log: Logs/08_ties_low.log.
* Tables A1-A6 are generated below in draft order and copied to Overleaf.
* Added sections can run independently.
* Figure A7 exports five-block Shapley decompositions of Table 3 Columns
* (2), (3), (5), (6) to results/figure_A7_review/table3_shapley.csv.
* Its log is Logs/08_shapley_distance_review.log; 09 draws manuscript subfigures.
********************************************************************************

clear all
set more off
set matsize 8000

local distance_var "Ihat_ig"
local code_dir `"`c(pwd)'"'

local replication_dir `"`code_dir'"'
local data_dir `"`replication_dir'/data"'
local tex_dir `"`code_dir'/results/tables"'
local result_dir `"`code_dir'/results/tables"'
cap mkdir `"`code_dir'/results"'
cap mkdir `"`tex_dir'"'
cap mkdir `"`result_dir'"'

foreach required in panel_individual.dta base_raw.dta end_raw.dta {
    capture confirm file `"`data_dir'/`required'"'
    if _rc {
        di as error "Missing required input: `data_dir'/`required'"
        exit 601
    }
}

********************************************************************************
* Table A1: Sensitivity to Buffers around Corner and Equal-Allocation Choices
********************************************************************************
* Run this section from Code. Use actual I and control for the saved CCEI benchmark M.
local code_dir `"`c(pwd)'"'
local data_dir `"`code_dir'/data"'
local tex_dir `"`code_dir'/results/tables"'
cap mkdir `"`tex_dir'"'
cap mkdir "Logs"
capture log close choice_buffers
log using "Logs/08_choice_buffers.log", name(choice_buffers) text replace

* Reuse Table 3's raw-choice definitions, adding inclusive payoff-share buffers.
tempfile baseline_shares choice_shares partner_shares
foreach wave in base end {
    use "`data_dir'/`wave'_raw.dta", clear
    keep if game_type == 1
    gen byte post = ("`wave'" == "end")
    assert !missing(coord_x, coord_y) & coord_x >= 0 & coord_y >= 0
    assert coord_x + coord_y > 0
    bysort id: assert _N == 18
    gen byte corner_0 = (coord_x == 0 | coord_y == 0)
    gen byte mid_0 = (coord_x == coord_y)
    * Integer multipliers include exact boundaries without floating-point drift.
    gen byte corner_025 = 40 * min(coord_x, coord_y) <= coord_x + coord_y
    gen byte mid_025 = 20 * abs(coord_x - coord_y) <= coord_x + coord_y
    gen byte corner_05 = 20 * min(coord_x, coord_y) <= coord_x + coord_y
    gen byte mid_05 = 10 * abs(coord_x - coord_y) <= coord_x + coord_y
    assert corner_0 <= corner_025 & corner_025 <= corner_05
    assert mid_0 <= mid_025 & mid_025 <= mid_05
    collapse (mean) corner_* mid_*, by(id post)
    if "`wave'" == "base" save `baseline_shares'
}
append using `baseline_shares'
isid id post
save `choice_shares'
rename id partner_id
save `partner_shares'

use "`data_dir'/panel_individual.dta", clear
isid id post
keep if !missing(Ihat_ig)
assert _N == 2560
egen long id_fe = group(id)

merge 1:1 id post using `choice_shares', keep(master match) assert(match using) nogen
foreach suffix in 0 025 05 {
    rename corner_`suffix' corner_`suffix'_i
    rename mid_`suffix' mid_`suffix'_i
}
merge m:1 partner_id post using `partner_shares', keep(master match) assert(match using) nogen
foreach suffix in 0 025 05 {
    rename corner_`suffix' corner_`suffix'_j
    rename mid_`suffix' mid_`suffix'_j
}
capture drop female_i_male_j male_i_female_j
gen byte female_i_male_j = (male_i == 0 & male_j == 1)
gen byte male_i_female_j = (male_i == 1 & male_j == 0)

* The benchmark comes from the validated full 651-donor CCEI calculation.
merge 1:1 id post using "IminusM_review/outputs/data/ccei_ra_candidate_analysis.dta", ///
    keepusing(M_ccei n_ccei_donors) keep(master match) assert(match using) nogen
assert n_ccei_donors == 651 & !missing(M_ccei)

local individual "mathscore_i mathscore_diff height_i height_diff outgoing_i outgoing_diff opened_i opened_diff agreeable_i agreeable_diff conscientious_i conscientious_diff stable_i stable_diff"
local gender "female_i_male_j male_i_female_j"
local friendship "inclass_n_friends_i inclass_n_diff inclass_popularity_i inclass_pop_diff"
local missing_controls "mathscore_diff_missing outgoing_diff_missing opened_diff_missing agreeable_diff_missing conscientious_diff_missing stable_diff_missing"
label var HighCCEI_both_high "\$Higher\ CCEI_i\$"
label var ccei_gap_ij "\$CCEI_i-CCEI_j\$"
label var M_ccei "\$M_{ig}\$"

local panel = 0
foreach suffix in 0 025 05 {
    local ++panel
    capture drop candidate_corner_i candidate_corner_diff candidate_mid_i candidate_mid_diff
    gen double candidate_corner_i = corner_`suffix'_i
    gen double candidate_corner_diff = corner_`suffix'_i - corner_`suffix'_j
    gen double candidate_mid_i = mid_`suffix'_i
    gen double candidate_mid_diff = mid_`suffix'_i - mid_`suffix'_j
    local shares "candidate_corner_i candidate_corner_diff candidate_mid_i candidate_mid_diff"
    eststo clear
    local col = 0
    foreach focal in HighCCEI_both_high ccei_gap_ij {
        forvalues spec = 2/3 {
            local ++col
            local controls "`individual' `friendship' `missing_controls' `shares'"
            local fe id_fe
            local singleton_option "keepsingletons"
            if `spec' == 2 {
                local controls "`controls' `gender'"
                local fe class
                local singleton_option ""
            }
            quietly reghdfe Ihat_ig `focal' M_ccei `controls', absorb(`fe') vce(cluster class) `singleton_option'
            assert e(sample) == 1
            assert e(N) == 2560 & e(N_clust) == 64
            quietly summarize Ihat_ig if e(sample)
            estadd scalar ymean = r(mean)
            estadd scalar ysd = r(sd)
            estimates store buffer`col'
        }
    }
    local title "Panel A: No buffer"
    local mode replace
    if `panel' == 2 local title "Panel B: 2.5-percentage-point buffer"
    if `panel' == 3 local title "Panel C: 5-percentage-point buffer"
    if `panel' > 1 local mode append
    local panel_header ""
    if `panel' == 1 {
        local outcome_mean : display %3.1f e(ymean)
        local outcome_sd : display %4.2f e(ysd)
        local panel_header "\multicolumn{5}{l}{\hspace{1em} Mean: `outcome_mean', SD: `outcome_sd'} \\ \midrule"
    }
    local panel_separator "\hline"
    if `panel' == 3 local panel_separator "\midrule"
    esttab buffer1 buffer2 buffer3 buffer4 using `"`tex_dir'/table_bargainingCCEI_buffers_M.tex"', `mode' ///
        b(3) se(3) star(+ 0.1 * 0.05 ** 0.01) label nogap compress noomitted substitute(\_ _) ///
        keep(HighCCEI_both_high ccei_gap_ij M_ccei) order(HighCCEI_both_high ccei_gap_ij M_ccei) ///
        fragment nomtitles nonumbers nolines ///
        stats(r2, fmt(3) labels("R-squared")) ///
        prehead("`panel_header'" "\multicolumn{5}{l}{\emph{`title'}} \\") prefoot("") postfoot("`panel_separator'")
}
* All twelve fits use the same dependent variable and estimation sample.
* Export the shared footer from the fitted models rather than hard-coding values.
tempname buffer_footer
file open `buffer_footer' using `"`tex_dir'/table_bargainingCCEI_buffers_M.tex"', write append
file write `buffer_footer' "N"
forvalues column = 1/4 {
    estimates restore buffer`column'
    file write `buffer_footer' " & " %9.0f (e(N))
}
file write `buffer_footer' "\\" _n
file write `buffer_footer' "Fixed effects & Class & Individual & Class & Individual \\" _n
file write `buffer_footer' "Individual and friendship controls & \checkmark & \checkmark & \checkmark & \checkmark \\" _n
file write `buffer_footer' "Corner/midpoint share controls & \checkmark & \checkmark & \checkmark & \checkmark \\" _n
file write `buffer_footer' "\bottomrule" _n
file close `buffer_footer'
copy `"`tex_dir'/table_bargainingCCEI_buffers_M.tex"' ///
    `"`code_dir'/../Overleaf/tables_2025/table_bargainingCCEI_buffers_M.tex"', replace
di as result "SUCCESS: exported the M-controlled buffer appendix table; N=2560, clusters=64."
log close choice_buffers


********************************************************************************
* Table A2: Baseline correlations, using placebo-adjusted preference distance I-M
********************************************************************************
local code_dir `"`c(pwd)'"'
local tex_dir `"`code_dir'/results/tables"'
use "`code_dir'/IminusM_review/outputs/data/ccei_ra_candidate_analysis.dta", clear
isid id post
assert n_ccei_donors == 651 & !missing(M_ccei)
keep if post == 0
assert _N == 1304
capture drop analysis_distance
gen double analysis_distance = Ihat_ig - M_ccei
label var ccei_i "CCEI"
label var RA_i "Risk attitude"
label var analysis_distance "Preference Distance"
label var inclass_n_friends_i "Out-degree"
label var inclass_popularity_i "In-degree"
label var male_i "Male"
label var height_i "Height"
label var mathscore_i "Math score"
label var RAT_strict_i "RAT score"
label var outgoing_i "Outgoing"
label var opened_i "Openness"
label var agreeable_i "Agreeableness"
label var conscientious_i "Conscientiousness"
label var stable_i "Emotional stability"
local col_vars "ccei_i RA_i analysis_distance inclass_n_friends_i inclass_popularity_i"
local row_vars "`col_vars' male_i height_i mathscore_i RAT_strict_i outgoing_i opened_i agreeable_i conscientious_i stable_i"

capture file close corrfile
file open corrfile using "`tex_dir'/table_correlation_IminusM.tex", write replace
file write corrfile "\begin{tabular}{lccccc}\toprule" _n
file write corrfile " "
foreach variable of local col_vars {
    local column_label : variable label `variable'
    file write corrfile " & `column_label'"
}
file write corrfile " \\" _n "\midrule" _n
local row = 1
foreach var1 of local row_vars {
    local row_label : variable label `var1'
    file write corrfile "`row_label'"
    local col = 1
    foreach var2 of local col_vars {
        if `col' < `row' {
            quietly pwcorr `var1' `var2', sig
            local rho = r(rho)
            local pval = r(sig)[2,1]
            local stars ""
            if `pval' < 0.01 local stars "**"
            else if `pval' < 0.05 local stars "*"
            else if `pval' < 0.10 local stars "+"
            local significance ""
            if "`stars'" != "" local significance "\sym{`stars'}"
            file write corrfile " & " %5.3f (`rho') "`significance'"
        }
        else file write corrfile " & "
        local ++col
    }
    file write corrfile " \\" _n
    local ++row
}
file write corrfile "\bottomrule\end{tabular}" _n
file close corrfile
copy "`tex_dir'/table_correlation_IminusM.tex" ///
    "`code_dir'/../Overleaf/tables_2025/table_correlation_IminusM.tex", replace

* Prepare Table 3 appendix tables and Shapley inputs.
* This setup and the mover/ties-low export below can run independently from Code.
local code_dir `"`c(pwd)'"'
local data_dir `"`code_dir'/data"'
local tex_dir `"`code_dir'/results/tables"'
local distance_var "Ihat_ig"
cap mkdir `"`tex_dir'"'
do "programs/prepare_table3_controls.do"

global ai_group = "mathscore_i mathscore_diff height_i height_diff outgoing_i outgoing_diff opened_i opened_diff agreeable_i agreeable_diff conscientious_i conscientious_diff stable_i stable_diff female_i_male_j male_i_female_j"
global ai_group_nogender = "mathscore_i mathscore_diff height_i height_diff outgoing_i outgoing_diff opened_i opened_diff agreeable_i agreeable_diff conscientious_i conscientious_diff stable_i stable_diff"
global ai_friend = "inclass_n_friends_i inclass_n_diff inclass_popularity_i inclass_pop_diff"
global ai_missing = "mathscore_diff_missing outgoing_diff_missing opened_diff_missing agreeable_diff_missing conscientious_diff_missing stable_diff_missing"
global ai_ra = "RA_i RA_diff"
global ai_share = "corner_share_i corner_share_diff mid_share_i mid_share_diff"
label var HighCCEI_both_low "\$Higher CCEI_i\$"
label var mathscore_i "\$Math score_i\$"
label var mathscore_diff "\$Math score_{diff}\$"
label var inclass_popularity_i "\$In-degree_i\$"
label var inclass_pop_diff "\$In-degree_{diff}\$"
label var female_i_male_j "\$(Female_i, Male_j)\$"
label var male_i_female_j "\$(Male_i, Female_j)\$"

********************************************************************************
* Table A3: Individual Rationality and Revealed-Preference Distance by Mover Status
********************************************************************************
* Actual I is the outcome; all columns control for the full 651-donor M.
* Individual, friendship and choice-share controls match 06; RA is excluded.
cap mkdir "Logs"
capture log close table3_extensions
log using "Logs/08_table3_extensions.log", name(table3_extensions) text replace
preserve
* Use the validated benchmark panel; the available-distance mask matches Table 3.
use "IminusM_review/outputs/data/ccei_ra_candidate_analysis.dta", clear
isid id post
assert sample_ccei == balanced_t3
gen byte available_t3 = !missing(Ihat_ig)
assert missing(I_ccei) == missing(Ihat_ig)
assert I_ccei == Ihat_ig if !missing(Ihat_ig)
assert n_ccei_donors == 651 & !missing(M_ccei)
local full_controls "$ai_group_nogender $ai_friend $ai_missing $ai_share"
local gender "female_i_male_j male_i_female_j"
local selected "mathscore_i mathscore_diff female_i_male_j male_i_female_j inclass_popularity_i inclass_pop_diff"
label var HighCCEI_both_high "\$Higher\ CCEI_i\$"
label var HighCCEI_both_low "\$Higher\ CCEI_i\$"
label var ccei_gap_ij "\$CCEI_i-CCEI_j\$"
label var M_ccei "\$M_{ig}\$"
label var female_i_male_j "\$(Female_i, Male_j)\$"
label var male_i_female_j "\$(Male_i, Female_j)\$"
label var mathscore_i "\$Math\ score_i\$"
label var mathscore_diff "\$Math\ score_{diff}\$"
label var inclass_popularity_i "\$In\text{-}degree_i\$"
label var inclass_pop_diff "\$In\text{-}degree_{diff}\$"

do "programs/hdfe_cluster_vce.do"

* Mover status: augment each of Table 3's six models with mover and its interaction.
assert inlist(mover, 0, 1)
bysort group_id post: assert _N == 2 & available_t3 == available_t3[1]
by group_id post: assert mover[1] + mover[2] == 1
by group_id post: assert abs(Ihat_ig[1] + Ihat_ig[2] - 1) < 1e-12 if available_t3
by group_id post: assert abs(M_ccei[1] + M_ccei[2] - 1) < 1e-12
capture drop higher_mover gap_mover
gen double higher_mover = HighCCEI_both_high * mover
gen double gap_mover = ccei_gap_ij * mover
label var mover "\$Mover_i\$"
label var higher_mover "\$Higher\ CCEI_i\times Mover_i\$"
label var gap_mover "\$(CCEI_i-CCEI_j)\times Mover_i\$"
eststo clear
local column = 0
foreach focal in HighCCEI_both_high ccei_gap_ij {
    local interaction higher_mover
    if "`focal'" == "ccei_gap_ij" local interaction gap_mover
    forvalues spec = 1/3 {
        local ++column
        if `spec' == 1 {
            quietly reghdfe `distance_var' `focal' mover `interaction' M_ccei if available_t3, ///
                absorb(class) vce(cluster class) keepmata
        }
        if `spec' == 2 {
            quietly reghdfe `distance_var' `focal' mover `interaction' M_ccei `full_controls' `gender' if available_t3, ///
                absorb(class) vce(cluster class) keepmata
        }
        if `spec' == 3 {
            quietly reghdfe `distance_var' `focal' mover `interaction' M_ccei `full_controls' if available_t3, ///
                absorb(id_fe) vce(cluster class) keepsingletons keepmata
        }
        local zero_option ""
        if `column' == 4 local zero_option "zero(gap_mover)"
        hdfe_cluster_vce class, `zero_option'
        assert !missing(_se[`focal'], _se[M_ccei])
        assert e(N) == 2560 & e(N_clust) == 64
        assert e(sample) == available_t3
        quietly summarize `distance_var' if e(sample)
        estadd scalar ymean = r(mean)
        estadd scalar ysd = r(sd)
        local fixed_label Class
        if `spec' == 3 local fixed_label Individual
        local check ""
        if `spec' >= 2 local check "\checkmark"
        estadd local fixed_effects "`fixed_label'"
        estadd local characteristics "`check'"
        estadd local choice_shares "`check'"
        estimates store mover`column'
    }
}
* The structural zero in Column (4) displays (0.000), without a test or star.
local outcome_mean : display %3.1f e(ymean)
local outcome_sd : display %4.2f e(ysd)
esttab mover1 mover2 mover3 mover4 mover5 mover6 using `"`tex_dir'/table_bargainingCCEI_mover_M.tex"', replace ///
    b(3) se(3) star(+ 0.1 * 0.05 ** 0.01) label nogap compress noomitted substitute(\_ _ "(.)" "(0.000)") ///
    keep(HighCCEI_both_high ccei_gap_ij mover higher_mover gap_mover M_ccei `selected') ///
    order(HighCCEI_both_high ccei_gap_ij mover higher_mover gap_mover M_ccei `selected') ///
    stats(N r2 fixed_effects characteristics choice_shares, fmt(0 3) ///
        labels("N" "R-squared" "Fixed effects" "Individual and friendship controls" "Corner/midpoint share controls")) ///
    fragment nomtitles nonumbers nolines ///
    prehead("\multicolumn{7}{l}{\hspace{1em} Mean: `outcome_mean', SD: `outcome_sd'} \\" "\midrule") ///
    prefoot("\midrule") postfoot("\bottomrule")
copy `"`tex_dir'/table_bargainingCCEI_mover_M.tex"' ///
    `"`code_dir'/../Overleaf/tables_2025/table_bargainingCCEI_mover_M.tex"', replace
restore
di as result "SUCCESS: exported Table A3; N=2560, clusters=64."
log close table3_extensions

********************************************************************************
* Table A4: Individual Characteristics and Changes in CCEI
* Baseline controls, then baseline controls plus changes, for 1,256 students.
* No fixed effects, partner characteristics, or within-pair differences enter.
********************************************************************************
preserve
local data_dir "data"
local out_dir "results/tables"
capture mkdir "results"
capture mkdir "`out_dir'"
tempfile coefficients
capture log close ccei_change
log using "`out_dir'/individual_ccei_change.log", name(ccei_change) text replace

use "`data_dir'/panel_individual.dta", clear
isid id post
bysort id (post): assert _N == 2 & post[1] == 0 & post[2] == 1
assert !missing(ccei_i)
bysort id (post): gen double ccei_change = ccei_i[2] - ccei_i[1]
bysort id: egen n_distance = total(!missing(Ihat_ig))
gen byte table3_sample = (n_distance == 2)


local student "male_i height_i mathscore_i outgoing_i opened_i agreeable_i conscientious_i stable_i inclass_n_friends_i inclass_popularity_i"
local missing_controls "mathscore_i_missing outgoing_i_missing opened_i_missing agreeable_i_missing conscientious_i_missing stable_i_missing"

foreach var in mathscore_i inclass_n_friends_i inclass_popularity_i {
    bysort id (post): gen double `var'_change = `var'[2] - `var'[1]
}

local student_chng "mathscore_i_change inclass_n_friends_i_change inclass_popularity_i_change"

keep if post == 0
isid id
assert _N == 1304
count if table3_sample
assert r(N) == 1256

label var male_i "Male"
label var height_i "Height"
label var mathscore_i "Math score"
label var outgoing_i "Outgoingness"
label var opened_i "Openness"
label var agreeable_i "Agreeableness"
label var conscientious_i "Conscientiousness"
label var stable_i "Emotional stability"
label var inclass_n_friends_i "Out-degree"
label var inclass_popularity_i "In-degree"
label var mathscore_i_change "Change in math score"
label var inclass_n_friends_i_change "Change in out-degree"
label var inclass_popularity_i_change "Change in in-degree"

eststo clear
eststo change1: regress ccei_change `student' `missing_controls' ///
    if table3_sample == 1, vce(cluster class)
eststo change2: regress ccei_change `student' `student_chng' `missing_controls' ///
    if table3_sample == 1, vce(cluster class)

postfile coefficient_file byte column str32 variable double beta se p N ///
    df clusters using `coefficients'
forvalues column = 1/2 {
    estimates restore change`column'
    assert e(N) == 1256 & e(N_clust) == 64
    local reported "`student'"
    if `column' == 2 local reported "`student' `student_chng'"
    foreach variable in `reported' {
        post coefficient_file (`column') ("`variable'") (_b[`variable']) ///
            (_se[`variable']) (2 * ttail(e(df_r), abs(_b[`variable'] / _se[`variable']))) ///
            (e(N)) (e(df_r)) (e(N_clust))
    }
    quietly summarize ccei_change if e(sample)
    estadd scalar mean_change = r(mean)
    estadd local class_fe "No"
    estadd local missing_indicators "Yes"
    estadd scalar class_clusters = e(N_clust)
}
postclose coefficient_file

esttab change1 change2, b(3) se(3) label ///
    keep(`student' `student_chng') order(`student' `student_chng') ///
    mtitles("Baseline" "Baseline + changes") star(+ 0.1 * 0.05 ** 0.01) ///
    stats(N r2 class_fe, labels("Individuals" "R-squared" "Class fixed effects") fmt(0 3 %9s))

esttab change1 change2 using "`out_dir'/table_individual_ccei_change.tex", replace ///
    b(3) se(3) keep(`student' `student_chng') order(`student' `student_chng') ///
    stats(N r2 mean_change, ///
    labels("N" "R-squared" "Mean change in CCEI") fmt(0 3 3)) ///
    nogap compress star(+ 0.1 * 0.05 ** 0.01) label ///
    nomtitles fragment nonumbers nolines prefoot("\midrule") postfoot("\bottomrule")
copy "`out_dir'/table_individual_ccei_change.tex" ///
    "../Overleaf/tables_2025/table_individual_ccei_change.tex", replace

use `coefficients', clear
export delimited using "`out_dir'/individual_ccei_change_coefficients.csv", replace
log close ccei_change
restore

********************************************************************************
* Table A5: alternative measures with full same-wave donor benchmarks.
* Run independently from Code after section 7 of 1_1_calculate_indices.R.
* HM/MaxMPI use results/benchmarks; RA retains its verified 651-donor benchmark.
* Actual distance is the outcome; six specifications match Table 3, excluding RA
* controls. All panels use Table 3's 2,560 defined CCEI-distance observations,
* retaining its 48 single-wave students under individual fixed effects.
********************************************************************************
local a5_code_dir `"`c(pwd)'"'
local a5_tex_dir `"`a5_code_dir'/results/tables"'
cap mkdir "Logs"
cap mkdir `"`a5_tex_dir'"'
capture log close alternative_full
log using "Logs/08_alternative_full.log", name(alternative_full) text replace
preserve
do "programs/prepare_table3_controls.do"

tempfile a5_panel a5_benchmark a5_results
gen byte available_t3 = !missing(Ihat_ig)
count if available_t3
assert r(N) == 2560
save `a5_panel'
foreach a5_measure in hm maxmpi ra {
    local a5_source "results/benchmarks/`a5_measure'/placebo_normalized_member_wave.dta"
    if "`a5_measure'" == "ra" local a5_source "IminusM_review/outputs/data/ra_placebo_member_wave.dta"
    use "`a5_source'", clear
    tostring group_id, replace format(%14.0f)
    tostring id, replace format(%7.0f)
    isid group_id post id
    assert _N == 2608 & n_all == 651 & !missing(M_all_imp)
    keep group_id post id I_actual M_all_imp
    rename I_actual a5_cached_`a5_measure'
    rename M_all_imp M_`a5_measure'
    save `a5_benchmark', replace
    use `a5_panel', clear
    capture drop M_`a5_measure'
    merge 1:1 group_id post id using `a5_benchmark', assert(match) nogen
    save `a5_panel', replace
}

gen double a5_I_hm = Ihat_hm_ig
gen double a5_I_maxmpi = Ihat_maxmpi_ig
gen double a5_RA_denom = (RA_i - RA_g)^2 + (RA_j - RA_g)^2
gen double a5_I_ra = (RA_i - RA_g)^2 / a5_RA_denom if a5_RA_denom > 0
foreach a5_measure in hm maxmpi ra {
    assert missing(a5_I_`a5_measure') == missing(a5_cached_`a5_measure')
    assert abs(a5_I_`a5_measure' - a5_cached_`a5_measure') < 2e-6 if !missing(a5_I_`a5_measure')
    bysort group_id post: assert abs(M_`a5_measure'[1] + M_`a5_measure'[2] - 1) < 1e-7
    assert !missing(a5_I_`a5_measure') if available_t3
}

local a5_individual "mathscore_i mathscore_diff height_i height_diff outgoing_i outgoing_diff opened_i opened_diff agreeable_i agreeable_diff conscientious_i conscientious_diff stable_i stable_diff"
local a5_friendship "inclass_n_friends_i inclass_n_diff inclass_popularity_i inclass_pop_diff"
local a5_missing "mathscore_diff_missing outgoing_diff_missing opened_diff_missing agreeable_diff_missing conscientious_diff_missing stable_diff_missing"
local a5_shares "corner_share_i corner_share_diff mid_share_i mid_share_diff"
local a5_gender "female_i_male_j male_i_female_j"
postfile a5_post str8 measure byte column double beta double se double p ///
    double beta_M double se_M double p_M double outcome_sd double focal_sd ///
    double standardized long N long clusters double r2 using `a5_results', replace
local a5_write "replace"
foreach a5_measure in hm maxmpi ra {
    local a5_high "HighHM_both_high"
    local a5_gap "hm_gap_ij"
    local a5_panel_name "A: HM-based distance"
    if "`a5_measure'" == "maxmpi" {
        local a5_high "HighMaxMPI_both_high"
        local a5_gap "maxmpi_gap_ij"
        local a5_panel_name "B: MaxMPI-based distance"
    }
    if "`a5_measure'" == "ra" {
        local a5_high "HighCCEI_both_high"
        local a5_gap "ccei_gap_ij"
        local a5_panel_name "C: Risk-aversion distance"
    }
    label var `a5_high' "Higher rationality"
    label var `a5_gap' "Rationality difference"
    label var M_`a5_measure' "\$M_{ig}\$"
    forvalues a5_column = 1/6 {
        local a5_spec = mod(`a5_column' - 1, 3) + 1
        local a5_focal "`a5_high'"
        if `a5_column' > 3 local a5_focal "`a5_gap'"
        local a5_controls ""
        local a5_effect "class"
        local a5_singletons ""
        if `a5_spec' > 1 local a5_controls "`a5_individual' `a5_friendship' `a5_missing' `a5_shares'"
        if `a5_spec' == 2 local a5_controls "`a5_controls' `a5_gender'"
        if `a5_spec' == 3 {
            local a5_effect "id_fe"
            local a5_singletons "keepsingletons"
        }
        quietly reghdfe a5_I_`a5_measure' `a5_focal' M_`a5_measure' `a5_controls' ///
            if available_t3, absorb(`a5_effect') vce(cluster class) `a5_singletons'
        assert e(N) == 2560 & e(N_clust) == 64
        assert e(sample) == available_t3
        local a5_b = _b[`a5_focal']
        local a5_s = _se[`a5_focal']
        local a5_p = 2 * ttail(e(df_r), abs(`a5_b' / `a5_s'))
        local a5_bM = _b[M_`a5_measure']
        local a5_sM = _se[M_`a5_measure']
        local a5_pM = 2 * ttail(e(df_r), abs(`a5_bM' / `a5_sM'))
        quietly summarize a5_I_`a5_measure' if e(sample)
        local a5_ymean = r(mean)
        local a5_ysd = r(sd)
        quietly summarize `a5_focal' if e(sample)
        local a5_xsd = r(sd)
        post a5_post ("`a5_measure'") (`a5_column') (`a5_b') (`a5_s') (`a5_p') ///
            (`a5_bM') (`a5_sM') (`a5_pM') (`a5_ysd') (`a5_xsd') ///
            (`a5_b' * `a5_xsd' / `a5_ysd') (e(N)) (e(N_clust)) (e(r2))
        estadd scalar ymean = `a5_ymean'
        estadd scalar ysd = `a5_ysd'
        estimates store a5_`a5_measure'_`a5_column'
    }
    local a5_mean : display %3.1f `a5_ymean'
    local a5_sd : display %4.2f `a5_ysd'
    esttab a5_`a5_measure'_1 a5_`a5_measure'_2 a5_`a5_measure'_3 ///
        a5_`a5_measure'_4 a5_`a5_measure'_5 a5_`a5_measure'_6 ///
        using `"`a5_tex_dir'/table_bargaining_alternatives_M.tex"', `a5_write' ///
        b(3) se(3) star(+ 0.1 * 0.05 ** 0.01) label fragment nomtitles nonumbers nolines nogap substitute(\_ _) ///
        keep(`a5_high' `a5_gap' M_`a5_measure') order(`a5_high' `a5_gap' M_`a5_measure') ///
        stats(N r2, fmt(0 3) labels("N" "R-squared")) ///
        prehead("\multicolumn{7}{l}{\emph{Panel `a5_panel_name'}} \\" ///
            "\multicolumn{7}{l}{\hspace{1em} Mean: `a5_mean', SD: `a5_sd'} \\") ///
        posthead("") prefoot("") postfoot("\midrule")
    local a5_write "append"
}
postclose a5_post
file open a5_footer using `"`a5_tex_dir'/table_bargaining_alternatives_M.tex"', write append
file write a5_footer "Fixed effects & Class & Class & Individual & Class & Class & Individual \\" _n
file write a5_footer "Individual and friendship controls & & \checkmark & \checkmark & & \checkmark & \checkmark \\" _n
file write a5_footer "Corner/midpoint share controls & & \checkmark & \checkmark & & \checkmark & \checkmark \\" _n
file write a5_footer "\bottomrule" _n
file close a5_footer
use `a5_results', clear
isid measure column
assert _N == 18
export delimited using `"`a5_tex_dir'/table_bargaining_alternatives_M.csv"', replace
copy `"`a5_tex_dir'/table_bargaining_alternatives_M.tex"' ///
    `"`a5_code_dir'/../Overleaf/tables_2025/table_bargaining_alternatives_M.tex"', replace
restore
di as result "SUCCESS: exported Table A5; all 18 fits match Table 3's N=2560 and 64 class clusters."
log close alternative_full

********************************************************************************
* Table A6: Individual Rationality and Revealed-Preference Distance: Strictly Higher CCEI
********************************************************************************
* Actual I is the outcome; all columns control for the full 651-donor M.
* Individual, friendship and choice-share controls match 06; RA is excluded.
local code_dir `"`c(pwd)'"'
local distance_var "Ihat_ig"
local tex_dir "results/tables"
cap mkdir "Logs"
capture log close ties_low
log using "Logs/08_ties_low.log", name(ties_low) text replace
preserve
do "programs/prepare_table3_controls.do"
gen byte available_t3 = !missing(`distance_var')
capture drop M_ccei n_ccei_donors
merge 1:1 id post using "IminusM_review/outputs/data/ccei_ra_candidate_analysis.dta", ///
    keepusing(M_ccei n_ccei_donors) assert(match) nogen
assert n_ccei_donors == 651 & !missing(M_ccei)
assert HighCCEI_both_low == (ccei_i > ccei_j)
local individual "mathscore_i mathscore_diff height_i height_diff outgoing_i outgoing_diff opened_i opened_diff agreeable_i agreeable_diff conscientious_i conscientious_diff stable_i stable_diff"
local friendship "inclass_n_friends_i inclass_n_diff inclass_popularity_i inclass_pop_diff"
local missing_controls "mathscore_diff_missing outgoing_diff_missing opened_diff_missing agreeable_diff_missing conscientious_diff_missing stable_diff_missing"
local shares "corner_share_i corner_share_diff mid_share_i mid_share_diff"
local full_controls "`individual' `friendship' `missing_controls' `shares'"
local gender "female_i_male_j male_i_female_j"
label var HighCCEI_both_low "\$Higher\ CCEI_i\$"
label var M_ccei "\$M_{ig}\$"

* Ties assigned Low: the three higher-CCEI specifications from Table 3.
eststo clear
eststo low1: reghdfe `distance_var' HighCCEI_both_low M_ccei if available_t3, absorb(class) vce(cluster class)
eststo low2: reghdfe `distance_var' HighCCEI_both_low M_ccei `full_controls' `gender' if available_t3, absorb(class) vce(cluster class)
eststo low3: reghdfe `distance_var' HighCCEI_both_low M_ccei `full_controls' if available_t3, absorb(id_fe) vce(cluster class) keepsingletons
foreach model in low1 low2 low3 {
    estimates restore `model'
    assert e(N) == 2560 & e(N_clust) == 64
    assert e(sample) == available_t3
}
foreach model in low1 low2 {
    estadd local fixed_effects "Class" : `model'
}
estadd local fixed_effects "Individual" : low3
foreach model in low2 low3 {
    estadd local characteristics "\checkmark" : `model'
    estadd local choice_shares "\checkmark" : `model'
}
esttab low1 low2 low3 using `"`tex_dir'/table_bargainingCCEI_bothlow_M.tex"', replace ///
    b(3) se(3) star(+ 0.1 * 0.05 ** 0.01) label nogap compress noomitted substitute(\_ _) ///
    keep(HighCCEI_both_low M_ccei) order(HighCCEI_both_low M_ccei) ///
    stats(N r2 fixed_effects characteristics choice_shares, fmt(0 3) ///
        labels("N" "R-squared" "Fixed effects" "Individual and friendship controls" "Corner/midpoint share controls")) ///
    fragment nomtitles nonumbers nolines prefoot("\midrule") postfoot("\bottomrule")

copy `"`tex_dir'/table_bargainingCCEI_bothlow_M.tex"' ///
    `"`code_dir'/../Overleaf/tables_2025/table_bargainingCCEI_bothlow_M.tex"', replace
restore
di as result "SUCCESS: exported Table A6 on Table 3's exact sample; N=2560, clusters=64."
log close ties_low

* Alternative-index Table 3
foreach measure in hm maxmpi {
    if "`measure'" == "hm" {
        local title "HM"
        local outcome "Ihat_hm_ig"
        local low "HighHM_both_low"
        label var HighHM_both_low "\$Higher (1-HM)_i\$"
    }
    else {
        local title "MaxMPI"
        local outcome "Ihat_maxmpi_ig"
        local low "HighMaxMPI_both_low"
        label var HighMaxMPI_both_low "\$Higher (1-MaxMPI)_i\$"
    }

    capture drop n_alt_distance balanced_alt
    bysort id: egen n_alt_distance = total(!missing(`outcome'))
    gen byte balanced_alt = (n_alt_distance == 2)

    * Both-high and continuous-gap models are generated by 99_21 below.
    eststo clear
    eststo al1: reghdfe `outcome' `low' if balanced_alt, absorb(class) vce(cluster class)
    * eststo al2: reghdfe `outcome' `low' $ai_group $ai_friend $ai_missing if balanced_alt, absorb(class) vce(cluster class)
    eststo al3: reghdfe `outcome' `low' $ai_group $ai_friend $ai_missing $ai_ra $ai_share if balanced_alt, absorb(class) vce(cluster class)
    eststo al4: reghdfe `outcome' `low' $ai_group_nogender $ai_friend $ai_missing $ai_ra $ai_share if balanced_alt, absorb(id_fe) vce(cluster class)
    foreach m in al1 al3 {
        estadd local fixed_effects "Class" : `m'
    }
    estadd local fixed_effects "Individual" : al4
    foreach m in al3 al4 {
        estadd local individual_controls "\checkmark" : `m'
        estadd local friendship_controls "\checkmark" : `m'
        estadd local ra_controls "\checkmark" : `m'
        estadd local share_controls "\checkmark" : `m'
    }
    esttab al1 al3 al4 using `"`tex_dir'/table_bargaining`title'_bothlow.tex"', replace ///
        b(3) se(3) stats(N r2 fixed_effects individual_controls friendship_controls ra_controls share_controls, ///
        labels("N" "R-squared" "Fixed effects" "Other individual characteristics" "Other friendship characteristics" "\$RA_i\$ controls" "Corner/midpoint share controls") fmt(0 3 %9s %9s %9s %9s %9s)) ///
        nogap compress star(+ 0.1 * 0.05 ** 0.01) label substitute(\_ _) ///
        keep(`low' mathscore_i mathscore_diff inclass_popularity_i inclass_pop_diff female_i_male_j male_i_female_j) ///
        order(`low' mathscore_i mathscore_diff female_i_male_j male_i_female_j inclass_popularity_i inclass_pop_diff) ///
        nomtitles fragment nonumbers nolines prefoot("\hline") postfoot("\hline \bottomrule")
}

* Refresh supplementary mover and robustness tables, retaining Shapley data.
preserve
    do "99_20_appendix_mover.do"
    do "99_21_appendix_robustness.do"
restore

tempfile table3_shapley_data
save `table3_shapley_data'

* Prepare supplementary collective-CCEI tables and Shapley data

use `"`data_dir'/panel_individual.dta"', clear

tempfile t5_shares t5_partner_shares t5_base_shares
preserve
    use `"`data_dir'/base_raw.dta"', clear
    keep if game_type == 1
    gen post = 0
    gen byte corner_share = (coord_x == 0 | coord_y == 0) if !missing(coord_x, coord_y)
    gen byte mid_share = (coord_x == coord_y) if !missing(coord_x, coord_y)
    collapse (mean) corner_share mid_share, by(id post)
    save `t5_base_shares'

    use `"`data_dir'/end_raw.dta"', clear
    keep if game_type == 1
    gen post = 1
    gen byte corner_share = (coord_x == 0 | coord_y == 0) if !missing(coord_x, coord_y)
    gen byte mid_share = (coord_x == coord_y) if !missing(coord_x, coord_y)
    collapse (mean) corner_share mid_share, by(id post)
    append using `t5_base_shares'
    save `t5_shares'
    rename id partner_id
    save `t5_partner_shares'
restore

merge m:1 id post using `t5_shares', keep(master match) nogen
rename corner_share corner_share_i
rename mid_share mid_share_i
merge m:1 partner_id post using `t5_partner_shares', keep(master match) nogen
rename corner_share corner_share_j
rename mid_share mid_share_j

foreach v in mathscore outgoing opened agreeable conscientious stable {
    replace `v'_i = 0 if missing(`v'_i)
    replace `v'_j = 0 if missing(`v'_j)
}
foreach v in ccei RA mathscore height outgoing opened agreeable conscientious stable inclass_n_friends inclass_popularity corner_share mid_share {
    capture drop `v'_max
    capture drop `v'_dist
    egen `v'_max = rowmax(`v'_i `v'_j)
    gen `v'_dist = abs(`v'_i - `v'_j)
}
capture drop male_diff
capture drop friend
gen male_diff = (male_i != male_j)
gen friend = (friendship >= 1)
bysort group_id post: keep if _n == 1
isid group_id post
egen long class_fe = group(class)
egen long pair_fe = group(group_id)

global ag_group = "mathscore_max mathscore_dist height_max height_dist male_diff outgoing_max outgoing_dist opened_max opened_dist agreeable_max agreeable_dist conscientious_max conscientious_dist stable_max stable_dist mathscore_diff_missing outgoing_diff_missing opened_diff_missing agreeable_diff_missing conscientious_diff_missing stable_diff_missing"
global ag_friend = "inclass_n_friends_max inclass_n_friends_dist inclass_popularity_max inclass_popularity_dist friend"
global ag_ra = "RA_max RA_dist"
global ag_share = "corner_share_max corner_share_dist mid_share_max mid_share_dist"

label var ccei_max "\$\text{CCEI}_{\text{max},gt}\$"
label var ccei_dist "\$\text{CCEI}_{\text{dist},gt}\$"
label var mathscore_max "\$\text{Math Score}_{\text{max},gt}\$"
label var mathscore_dist "\$\text{Math Score}_{\text{dist},gt}\$"
label var height_max "Max height"
label var height_dist "Diff. in height"
label var male_diff "Different gender"
label var outgoing_max "Max extraversion"
label var outgoing_dist "Diff. in extraversion"
label var opened_max "Max openness"
label var opened_dist "Diff. in openness"
label var agreeable_max "Max agreeableness"
label var agreeable_dist "Diff. in agreeableness"
label var conscientious_max "Max conscientiousness"
label var conscientious_dist "Diff. in conscientiousness"
label var stable_max "Max emotional stability"
label var stable_dist "Diff. in emotional stability"
label var inclass_n_friends_max "Max number of friends"
label var inclass_n_friends_dist "Diff. in number of friends"
label var inclass_popularity_max "Max in-degree"
label var inclass_popularity_dist "Diff. in in-degree"
label var friend "Friendship tie"
label var RA_max "\$\text{RA}_{\text{max},gt}\$"
label var RA_dist "\$\text{RA}_{\text{dist},gt}\$"
label var corner_share_max "Max corner share"
label var corner_share_dist "Diff. in corner share"
label var mid_share_max "Max midpoint share"
label var mid_share_dist "Diff. in midpoint share"

* Supplementary table: full collective-CCEI specification

eststo clear
eststo: reghdfe ccei_g ccei_max ccei_dist, absorb(class_fe) vce(cluster class_fe)
eststo: reghdfe ccei_g ccei_max ccei_dist $ag_group $ag_friend, absorb(class_fe) vce(cluster class_fe)
eststo: reghdfe ccei_g ccei_max ccei_dist $ag_group $ag_friend $ag_ra $ag_share, absorb(class_fe) vce(cluster class_fe)
eststo: reghdfe ccei_g ccei_max ccei_dist $ag_group $ag_friend $ag_ra $ag_share, absorb(pair_fe) vce(cluster class_fe)
esttab using `"`tex_dir'/final_collective_ccei_full.tex"', replace ///
    b(3) se(3) stats(N r2, labels("N" "R-squared") fmt(0 3)) ///
    nogap compress star(+ 0.1 * 0.05 ** 0.01) label ///
    order(ccei_max ccei_dist mathscore_max mathscore_dist height_max height_dist male_diff outgoing_max outgoing_dist opened_max opened_dist agreeable_max agreeable_dist conscientious_max conscientious_dist stable_max stable_dist inclass_n_friends_max inclass_n_friends_dist inclass_popularity_max inclass_popularity_dist friend RA_max RA_dist corner_share_max corner_share_dist mid_share_max mid_share_dist) ///
    drop(*_missing) noomitted nobaselevels nomtitles fragment nonumbers nolines ///
    prefoot("\midrule") postfoot("\bottomrule") substitute(\_ _)

* Alternative-index Table 5
gen double hm_r_i = 1 - hm_i / 18
gen double hm_r_j = 1 - hm_j / 18
gen double hm_r_g = 1 - hm_g / 18
gen double maxmpi_r_i = 1 - maxmpi_i
gen double maxmpi_r_j = 1 - maxmpi_j
gen double maxmpi_r_g = 1 - maxmpi_g

foreach measure in hm maxmpi {
    if "`measure'" == "hm" {
        local title "hm"
        local label "HM"
    }
    else {
        local title "revmaxmpi"
        local label "RevMaxMPI"
    }
    egen `measure'_r_max = rowmax(`measure'_r_i `measure'_r_j)
    egen `measure'_r_min = rowmin(`measure'_r_i `measure'_r_j)
    gen double `measure'_r_dist = abs(`measure'_r_i - `measure'_r_j)
    label var `measure'_r_max "\$\text{`label'}_{\text{max},gt}\$"
    label var `measure'_r_min "\$\text{`label'}_{\text{min},gt}\$"
    label var `measure'_r_dist "\$\text{`label'}_{\text{dist},gt}\$"

    foreach form in highlow maxdist {
        if "`form'" == "highlow" local focal "`measure'_r_max `measure'_r_min"
        else local focal "`measure'_r_max `measure'_r_dist"
        eststo clear
        eststo a1: reghdfe `measure'_r_g `focal', absorb(class_fe) vce(cluster class_fe)
        eststo a2: reghdfe `measure'_r_g `focal' $ag_group $ag_friend, absorb(class_fe) vce(cluster class_fe)
        eststo a3: reghdfe `measure'_r_g `focal' $ag_group $ag_friend $ag_ra $ag_share, absorb(class_fe) vce(cluster class_fe)
        eststo a4: reghdfe `measure'_r_g `focal' $ag_group $ag_friend $ag_ra $ag_share, absorb(pair_fe) vce(cluster class_fe)
        foreach m in a1 a2 a3 {
            estadd local fixed_effects "Class" : `m'
        }
        estadd local fixed_effects "Pair" : a4
        foreach m in a2 a3 a4 {
            estadd local student_controls "\checkmark" : `m'
        }
        foreach m in a3 a4 {
            estadd local ra_controls "\checkmark" : `m'
            estadd local share_controls "\checkmark" : `m'
        }
        esttab a1 a2 a3 a4 using `"`tex_dir'/final_collective_`title'_`form'.tex"', replace ///
            b(3) se(3) stats(N r2 fixed_effects student_controls ra_controls share_controls, ///
            labels("N" "R-squared" "Fixed effects" "Student and friendship controls" "RA controls" "Corner/midpoint share controls") fmt(0 3 %9s %9s %9s %9s)) ///
            nogap compress star(+ 0.1 * 0.05 ** 0.01) label ///
            keep(`focal') order(`focal') prefoot("\midrule") postfoot("\bottomrule") ///
            nomtitles fragment nonumbers nolines substitute(\_ _)
    }
}

tempfile table5_shapley_data
save `table5_shapley_data'

* Table 5 Shapley decomposition

use `table5_shapley_data', clear
capture drop FE_pair_*
quietly tabulate pair_fe, generate(FE_pair_)
unab table5_pair_dummies : FE_pair_*
local table5_pair_base : word 1 of `table5_pair_dummies'
local G_PAIR_FE : list table5_pair_dummies - table5_pair_base
local G_CHAR_T5 "$ag_group $ag_friend"
local G_RA_T5 "$ag_ra"
local G_SHARE_T5 "$ag_share"

foreach measure in ccei hm maxmpi {
    if "`measure'" == "ccei" {
        local outcome "ccei_g"
        local focal "ccei_max ccei_dist"
        local block_label "CCEI"
        local file_stem "shapley_collective_ccei"
    }
    else if "`measure'" == "hm" {
        local outcome "hm_r_g"
        local focal "hm_r_max hm_r_dist"
        local block_label "HM Index"
        local file_stem "shapley_collective_hm"
    }
    else {
        local outcome "maxmpi_r_g"
        local focal "maxmpi_r_max maxmpi_r_dist"
        local block_label "RevMaxMPI"
        local file_stem "shapley_collective_revmaxmpi"
    }

    reghdfe `outcome' `focal' $ag_group $ag_friend $ag_ra $ag_share, ///
        absorb(pair_fe) vce(cluster class_fe)
    scalar target_r2 = e(r2)
    scalar target_n = e(N)

    local TABLE5_GROUPS "`focal', `G_CHAR_T5', `G_RA_T5', `G_SHARE_T5', `G_PAIR_FE'"
    reg `outcome' `focal' `G_CHAR_T5' `G_RA_T5' `G_SHARE_T5' `G_PAIR_FE', ///
        vce(cluster class_fe)
    assert e(N) == target_n
    assert abs(e(r2) - target_r2) < 1e-10
    shapley2, stat(r2) group("`TABLE5_GROUPS'")

    matrix GCSh = e(shapley)
    matrix GCSr = e(shapley_rel)
    if rowsof(GCSh) == 1 matrix GCSh = GCSh'
    if rowsof(GCSr) == 1 matrix GCSr = GCSr'

    preserve
    clear
    set obs 5
    gen str40 block = ""
    replace block = "`block_label'" in 1
    replace block = "Group/Friendship" in 2
    replace block = "Risk Aversion" in 3
    replace block = "Corner/Midpoint Shares" in 4
    replace block = "Pair FE" in 5
    svmat double GCSh
    rename GCSh1 shapley_value
    svmat double GCSr
    rename GCSr1 shapley_share
    gen shapley_percent = 100 * shapley_share
    egen total_r2 = total(shapley_value)
    export excel block shapley_value shapley_percent total_r2 ///
        using `"`result_dir'/`file_stem'.xlsx"', firstrow(variables) replace
    export delimited block shapley_value shapley_percent total_r2 ///
        using `"`result_dir'/`file_stem'.csv"', replace
    restore
}

* Table 3 Shapley decomposition

use `table3_shapley_data', clear
local G_CHAR_T3 "$ai_group_nogender $ai_friend $ai_missing"
local G_RA_T3 "$ai_ra"
local G_SHARE_T3 "$ai_share"

foreach measure in ccei hm maxmpi {
    if "`measure'" == "ccei" {
        local outcome "`distance_var'"
        local high_var "HighCCEI_both_high"
        local low_var "HighCCEI_both_low"
        local gap_var "ccei_gap_ij"
        local block_label "CCEI"
        local file_stem "shapley_bargaining_index"
        local gap_suffix "_cceidiff"
    }
    else if "`measure'" == "hm" {
        local outcome "Ihat_hm_ig"
        local high_var "HighHM_both_high"
        local low_var "HighHM_both_low"
        local gap_var "hm_gap_ij"
        local block_label "HM Index"
        local file_stem "shapley_bargaining_hm"
        local gap_suffix "_hmdiff"
    }
    else {
        local outcome "Ihat_maxmpi_ig"
        local high_var "HighMaxMPI_both_high"
        local low_var "HighMaxMPI_both_low"
        local gap_var "maxmpi_gap_ij"
        local block_label "RevMaxMPI"
        local file_stem "shapley_bargaining_revmaxmpi"
        local gap_suffix "_revmaxmpidiff"
    }

    capture drop balanced_main n_main_distance FE_id_*
    bysort id: egen n_main_distance = total(!missing(`outcome'))
    gen byte balanced_main = (n_main_distance == 2)
    quietly tabulate id_fe if balanced_main, generate(FE_id_)
    unab table3_id_dummies : FE_id_*
    local table3_id_base : word 1 of `table3_id_dummies'
    local G_INDIVIDUAL_FE : list table3_id_dummies - table3_id_base

    foreach definition in bothhigh bothlow gap {
        if "`definition'" == "bothhigh" {
            local focal "`high_var'"
            local file_suffix ""
        }
        else if "`definition'" == "bothlow" {
            local focal "`low_var'"
            local file_suffix "_bothlow"
        }
        else {
            local focal "`gap_var'"
            local file_suffix "`gap_suffix'"
        }

        reghdfe `outcome' `focal' $ai_group_nogender $ai_friend $ai_missing $ai_ra $ai_share ///
            if balanced_main, absorb(id_fe) vce(cluster class)
        scalar target_r2 = e(r2)
        scalar target_n = e(N)

        local TABLE3_GROUPS "`focal', `G_CHAR_T3', `G_RA_T3', `G_SHARE_T3', `G_INDIVIDUAL_FE'"
        reg `outcome' `focal' `G_CHAR_T3' `G_RA_T3' `G_SHARE_T3' `G_INDIVIDUAL_FE' ///
            if balanced_main, vce(cluster class)
        assert e(N) == target_n
        assert abs(e(r2) - target_r2) < 1e-10
        shapley2, stat(r2) group("`TABLE3_GROUPS'")

        matrix BISh = e(shapley)
        matrix BISr = e(shapley_rel)
        if rowsof(BISh) == 1 matrix BISh = BISh'
        if rowsof(BISr) == 1 matrix BISr = BISr'

        preserve
        clear
        set obs 5
        gen str40 block = ""
        replace block = "`block_label'" in 1
        replace block = "Individual/Friendship" in 2
        replace block = "Risk Aversion" in 3
        replace block = "Corner/Midpoint Shares" in 4
        replace block = "Individual FE" in 5
        svmat double BISh
        rename BISh1 shapley_value
        svmat double BISr
        rename BISr1 shapley_share
        gen shapley_percent = 100 * shapley_share
        egen total_r2 = total(shapley_value)
        export excel block shapley_value shapley_percent total_r2 ///
            using `"`result_dir'/`file_stem'`file_suffix'.xlsx"', firstrow(variables) replace
        export delimited block shapley_value shapley_percent total_r2 ///
            using `"`result_dir'/`file_stem'`file_suffix'.csv"', replace
        restore
    }
}
* c_Ng sensitivity analysis
local cng_dir `"`tex_dir'/c_Ng"'
cap mkdir `"`cng_dir'"'

use `"`data_dir'/panel_individual.dta"', clear

tempfile t7_shares t7_partner_shares t7_base_shares
preserve
    use `"`data_dir'/base_raw.dta"', clear
    keep if game_type == 1
    gen post = 0
    gen byte corner_share = (coord_x == 0 | coord_y == 0) if !missing(coord_x, coord_y)
    gen byte mid_share = (coord_x == coord_y) if !missing(coord_x, coord_y)
    collapse (mean) corner_share mid_share, by(id post)
    save `t7_base_shares'

    use `"`data_dir'/end_raw.dta"', clear
    keep if game_type == 1
    gen post = 1
    gen byte corner_share = (coord_x == 0 | coord_y == 0) if !missing(coord_x, coord_y)
    gen byte mid_share = (coord_x == coord_y) if !missing(coord_x, coord_y)
    collapse (mean) corner_share mid_share, by(id post)
    append using `t7_base_shares'
    save `t7_shares'
    rename id partner_id
    save `t7_partner_shares'
restore

merge m:1 id post using `t7_shares', keep(master match) nogen
rename corner_share corner_share_i
rename mid_share mid_share_i
merge m:1 partner_id post using `t7_partner_shares', keep(master match) nogen
rename corner_share corner_share_j
rename mid_share mid_share_j

foreach v in mathscore outgoing opened agreeable conscientious stable {
    replace `v'_i = 0 if missing(`v'_i)
    replace `v'_j = 0 if missing(`v'_j)
}
foreach v in ccei RA mathscore height outgoing opened agreeable conscientious stable inclass_n_friends inclass_popularity corner_share mid_share {
    capture drop `v'_max
    capture drop `v'_dist
    egen `v'_max = rowmax(`v'_i `v'_j)
    gen `v'_dist = abs(`v'_i - `v'_j)
}
capture drop male_diff
capture drop friend
gen male_diff = (male_i != male_j)
gen friend = (friendship >= 1)
bysort group_id post: keep if _n == 1
isid group_id post

gen double hm_r_i = 1 - hm_i / 18
gen double hm_r_j = 1 - hm_j / 18
gen double maxmpi_r_i = 1 - maxmpi_i
gen double maxmpi_r_j = 1 - maxmpi_j
gen double c_hm_r_Ng = 1 - c_hm_Ng / 18
gen double c_maxmpi_r_Ng = 1 - c_maxmpi_Ng
foreach measure in hm maxmpi {
    egen `measure'_r_max = rowmax(`measure'_r_i `measure'_r_j)
    gen double `measure'_r_dist = abs(`measure'_r_i - `measure'_r_j)
}

assert !missing(c_Ng)
assert inrange(c_Ng, 0, 1)

egen long class_fe = group(class)
egen long pair_fe = group(group_id)

global cng_group = "mathscore_max mathscore_dist height_max height_dist male_diff outgoing_max outgoing_dist opened_max opened_dist agreeable_max agreeable_dist conscientious_max conscientious_dist stable_max stable_dist mathscore_diff_missing outgoing_diff_missing opened_diff_missing agreeable_diff_missing conscientious_diff_missing stable_diff_missing"
global cng_friend = "inclass_n_friends_max inclass_n_friends_dist inclass_popularity_max inclass_popularity_dist friend"
global cng_ra = "RA_max RA_dist"
global cng_share = "corner_share_max corner_share_dist mid_share_max mid_share_dist"

label var c_Ng "\$c_{Ng,t}\$"
label var ccei_max "\$\text{CCEI}_{\text{max},gt}\$"
label var ccei_dist "\$\text{CCEI}_{\text{dist},gt}\$"

quietly summarize c_Ng, detail
di as result "c_Ng observations = " r(N)
di as result "c_Ng mean = " %9.4f r(mean) ", sd = " %9.4f r(sd)
count if c_Ng <= 1e-6
di as result "c_Ng approximately zero = " r(N)

eststo clear
eststo cng1: reghdfe c_Ng ccei_max ccei_dist, absorb(class_fe) vce(cluster class_fe)
estadd local fixed_effects "Class"
estadd local student_controls ""
estadd local ra_controls ""
estadd local share_controls ""
eststo cng2: reghdfe c_Ng ccei_max ccei_dist $cng_group $cng_friend, absorb(class_fe) vce(cluster class_fe)
estadd local fixed_effects "Class"
estadd local student_controls "\checkmark"
estadd local ra_controls ""
estadd local share_controls ""
eststo cng3: reghdfe c_Ng ccei_max ccei_dist $cng_group $cng_friend $cng_ra $cng_share, absorb(class_fe) vce(cluster class_fe)
estadd local fixed_effects "Class"
estadd local student_controls "\checkmark"
estadd local ra_controls "\checkmark"
estadd local share_controls "\checkmark"
eststo cng4: reghdfe c_Ng ccei_max ccei_dist $cng_group $cng_friend $cng_ra $cng_share, absorb(pair_fe) vce(cluster class_fe)
estadd local fixed_effects "Pair"
estadd local student_controls "\checkmark"
estadd local ra_controls "\checkmark"
estadd local share_controls "\checkmark"

esttab cng1 cng2 cng3 cng4 using `"`cng_dir'/final_collective_cNg.tex"', replace ///
    b(3) se(3) ///
    stats(N r2 fixed_effects student_controls ra_controls share_controls, ///
        labels("N" "R-squared" "Fixed effects" ///
            "Student and friendship controls" "RA controls" ///
            "Corner/midpoint share controls") ///
        fmt(0 3 0 0 0 0)) ///
    nogap compress star(+ 0.1 * 0.05 ** 0.01) label ///
    keep(ccei_max ccei_dist) prefoot("\hline") postfoot("\hline \bottomrule") ///
    nomtitles fragment nonumbers nolines substitute(\_ _)

esttab cng1 cng2 cng3 cng4 using `"`cng_dir'/final_collective_cNg_full.tex"', replace ///
    b(3) se(3) stats(N r2, labels("N" "R-squared") fmt(0 3)) ///
    nogap compress star(+ 0.1 * 0.05 ** 0.01) label ///
    drop(*_missing) noomitted nobaselevels nomtitles fragment nonumbers nolines ///
    prefoot("\midrule") postfoot("\bottomrule") substitute(\_ _)

estimates restore cng4

capture drop FE_pair_*
quietly tabulate pair_fe, generate(FE_pair_)
unab cng_pair_dummies : FE_pair_*
local cng_pair_base : word 1 of `cng_pair_dummies'
local G_PAIR_FE : list cng_pair_dummies - cng_pair_base
local G_CHAR "$cng_group $cng_friend"
local G_RA "$cng_ra"
local G_SHARE "$cng_share"

foreach measure in ccei hm maxmpi {
    if "`measure'" == "ccei" {
        local outcome "c_Ng"
        local focal "ccei_max ccei_dist"
        local block_label "Individual CCEI"
        local file_stem "shapley_collective_cNg"
    }
    else if "`measure'" == "hm" {
        local outcome "c_hm_r_Ng"
        local focal "hm_r_max hm_r_dist"
        local block_label "Individual HM Index"
        local file_stem "shapley_collective_cNg_hm"
    }
    else {
        local outcome "c_maxmpi_r_Ng"
        local focal "maxmpi_r_max maxmpi_r_dist"
        local block_label "Individual RevMaxMPI"
        local file_stem "shapley_collective_cNg_revmaxmpi"
    }

    reghdfe `outcome' `focal' $cng_group $cng_friend $cng_ra $cng_share, ///
        absorb(pair_fe) vce(cluster class_fe)
    scalar target_r2 = e(r2)
    scalar target_n = e(N)

    local CNG_GROUPS "`focal', `G_CHAR', `G_RA', `G_SHARE', `G_PAIR_FE'"
    reg `outcome' `focal' `G_CHAR' `G_RA' `G_SHARE' `G_PAIR_FE', ///
        vce(cluster class_fe)
    assert e(N) == target_n
    assert abs(e(r2) - target_r2) < 1e-10
    shapley2, stat(r2) group("`CNG_GROUPS'")

    matrix CNGSh = e(shapley)
    matrix CNGSr = e(shapley_rel)
    if rowsof(CNGSh) == 1 matrix CNGSh = CNGSh'
    if rowsof(CNGSr) == 1 matrix CNGSr = CNGSr'

    preserve
    clear
    set obs 5
    gen str40 block = ""
    replace block = "`block_label'" in 1
    replace block = "Group/Friendship" in 2
    replace block = "Risk Aversion" in 3
    replace block = "Corner/Midpoint Shares" in 4
    replace block = "Pair FE" in 5
    svmat double CNGSh
    rename CNGSh1 shapley_value
    svmat double CNGSr
    rename CNGSr1 shapley_share
    gen shapley_percent = 100 * shapley_share
    egen total_r2 = total(shapley_value)
    export excel block shapley_value shapley_percent total_r2 ///
        using `"`cng_dir'/`file_stem'.xlsx"', firstrow(variables) replace
    export delimited block shapley_value shapley_percent total_r2 ///
        using `"`cng_dir'/`file_stem'.csv"', replace
    restore
}

* Alternative-index c_Ng tables
foreach measure in hm maxmpi {
    if "`measure'" == "hm" {
        local outcome "c_hm_r_Ng"
        local focal "hm_r_max hm_r_dist"
        local title "hm"
        label var hm_r_max "\$\text{HM}_{\text{max},gt}\$"
        label var hm_r_dist "\$\text{HM}_{\text{dist},gt}\$"
    }
    else {
        local outcome "c_maxmpi_r_Ng"
        local focal "maxmpi_r_max maxmpi_r_dist"
        local title "revmaxmpi"
        label var maxmpi_r_max "\$\text{RevMaxMPI}_{\text{max},gt}\$"
        label var maxmpi_r_dist "\$\text{RevMaxMPI}_{\text{dist},gt}\$"
    }

    eststo clear
    eststo cng1: reghdfe `outcome' `focal', absorb(class_fe) vce(cluster class_fe)
    estadd local fixed_effects "Class"
    estadd local student_controls ""
    estadd local ra_controls ""
    estadd local share_controls ""
    eststo cng2: reghdfe `outcome' `focal' $cng_group $cng_friend, absorb(class_fe) vce(cluster class_fe)
    estadd local fixed_effects "Class"
    estadd local student_controls "\checkmark"
    estadd local ra_controls ""
    estadd local share_controls ""
    eststo cng3: reghdfe `outcome' `focal' $cng_group $cng_friend $cng_ra $cng_share, absorb(class_fe) vce(cluster class_fe)
    estadd local fixed_effects "Class"
    estadd local student_controls "\checkmark"
    estadd local ra_controls "\checkmark"
    estadd local share_controls "\checkmark"
    eststo cng4: reghdfe `outcome' `focal' $cng_group $cng_friend $cng_ra $cng_share, absorb(pair_fe) vce(cluster class_fe)
    estadd local fixed_effects "Pair"
    estadd local student_controls "\checkmark"
    estadd local ra_controls "\checkmark"
    estadd local share_controls "\checkmark"

    esttab cng1 cng2 cng3 cng4 using `"`cng_dir'/final_collective_cNg_`title'.tex"', replace ///
        b(3) se(3) stats(N r2 fixed_effects student_controls ra_controls share_controls, ///
        labels("N" "R-squared" "Fixed effects" "Student and friendship controls" "RA controls" "Corner/midpoint share controls") ///
        fmt(0 3 %9s %9s %9s %9s)) ///
        nogap compress star(+ 0.1 * 0.05 ** 0.01) label ///
        keep(`focal') order(`focal') prefoot("\hline") postfoot("\hline \bottomrule") ///
        nomtitles fragment nonumbers nolines substitute(\_ _)
}


* Collective-outcomes appendix table: Low--High is the omitted category.
* Run independently from Code after 11_collective_quality.do.
local code_dir `"`c(pwd)'"'
local collective_dir "results/new_indices/collective_rationality_summary"
local tex_dir "results/tables"
tempfile collective_diagnostics
import delimited using "`collective_dir'/table5_diagnostics.csv", clear asdouble
keep if inrange(column, 1, 3)
isid outcome column
assert _N == 6 & n == 1304 & clusters == 64 & !missing(r2)
save `collective_diagnostics'
import delimited using "`collective_dir'/table5_coefficients.csv", clear asdouble
keep if inrange(column, 1, 3)
isid outcome column term
assert _N == 12 & inlist(outcome, "ccei", "ceiv")
assert inlist(term, "low_low", "high_high")
assert !missing(estimate, se, p) & se > 0 & inrange(p, 0, 1)
merge m:1 outcome column using `collective_diagnostics', assert(match) nogen
local bs = char(92)
gen str40 b_text = strtrim(string(estimate, "%9.3f")) + "`bs'textsuperscript{" + ///
    cond(p < .01, "**", cond(p < .05, "*", cond(p < .1, "+", ""))) + "}"
gen str14 se_text = "(" + strtrim(string(se, "%9.3f")) + ")"
gen str12 n_text = strtrim(string(n, "%9.0fc"))
gen str12 r2_text = strtrim(string(r2, "%9.3f"))
tempname category_table
file open `category_table' using "`tex_dir'/collective_ccei_ceiv_categories.tex", write replace
file write `category_table' "`bs'begin{tabular}{lccc}`bs'toprule" _n
file write `category_table' "& `bs'multicolumn{3}{c}{Individual CCEI category dummies}`bs'`bs'" _n
file write `category_table' "`bs'cmidrule(lr){2-4}" _n "& (1) & (2) & (3)`bs'`bs'`bs'midrule" _n
foreach outcome in ccei ceiv {
    local panel = cond("`outcome'" == "ccei", "A: Group CCEI", "B: Group CEIV")
    file write `category_table' "`bs'multicolumn{4}{l}{`bs'textit{Panel `panel'}}`bs'`bs'[3pt]" _n
    foreach term in low_low high_high {
        local label = cond("`term'" == "low_low", "Low--Low pair", "High--High pair")
        foreach stat in b_text se_text {
            local row_label = cond("`stat'" == "b_text", "`label'", "")
            file write `category_table' "`row_label'"
            forvalues column = 1/3 {
                quietly levelsof `stat' if outcome == "`outcome'" & column == `column' & term == "`term'", local(cell) clean
                file write `category_table' " & `cell'"
            }
            file write `category_table' "`bs'`bs'" _n
        }
    }
    foreach stat in n_text r2_text {
        local label = cond("`stat'" == "n_text", "Observations", "R-squared")
        file write `category_table' "`label'"
        forvalues column = 1/3 {
            quietly levelsof `stat' if outcome == "`outcome'" & column == `column' & term == "high_high", local(cell) clean
            file write `category_table' " & `cell'"
        }
        file write `category_table' "`bs'`bs'" _n
    }
    file write `category_table' "`bs'midrule" _n
}
file write `category_table' "Fixed effects & Class & Class & Pair`bs'`bs'" _n
file write `category_table' "Student and friendship controls &  & " (char(36)) "`bs'checkmark" ///
    (char(36)) " & " (char(36)) "`bs'checkmark" (char(36)) "`bs'`bs'" _n
file write `category_table' "Corner/midpoint share controls &  & " (char(36)) "`bs'checkmark" ///
    (char(36)) " & " (char(36)) "`bs'checkmark" (char(36)) "`bs'`bs'" _n
file write `category_table' "`bs'bottomrule`bs'end{tabular}" _n
file close `category_table'
copy "`tex_dir'/collective_ccei_ceiv_categories.tex" "../Overleaf/tables_2025/collective_ccei_ceiv_categories.tex", replace
di as result "SUCCESS: exported collective-outcomes appendix table with Low--High omitted."


********************************************************************************
* Figure A7: Table 3 Columns (2), (3), (5), (6), with FE as a Shapley block.
* Run independently from Code. 09 exports separate panels for the manuscript.
* All 32 coalitions use the same sample; contributions sum to overall R-squared.
********************************************************************************
clear
set more off
cap mkdir "Logs"
capture log close distance_shapley_review
log using "Logs/08_shapley_distance_review.log", name(distance_shapley_review) text replace
do "programs/prepare_table3_controls.do"
capture drop M_ccei n_ccei_donors
merge 1:1 id post using "IminusM_review/outputs/data/ccei_ra_candidate_analysis.dta", ///
    keepusing(M_ccei n_ccei_donors) assert(match) nogen
assert n_ccei_donors == 651 & !missing(M_ccei)
keep if !missing(Ihat_ig)
assert _N == 2560
local characteristics "mathscore_i mathscore_diff height_i height_diff outgoing_i outgoing_diff opened_i opened_diff agreeable_i agreeable_diff conscientious_i conscientious_diff stable_i stable_diff inclass_n_friends_i inclass_n_diff inclass_popularity_i inclass_pop_diff mathscore_diff_missing outgoing_diff_missing opened_diff_missing agreeable_diff_missing conscientious_diff_missing stable_diff_missing"
local shares "corner_share_i corner_share_diff mid_share_i mid_share_diff"
local gender "female_i_male_j male_i_female_j"
foreach variable in Ihat_ig HighCCEI_both_high ccei_gap_ij M_ccei `characteristics' `shares' `gender' {
    assert !missing(`variable')
}
tempfile review_results
tempname review_output coalition_r2
postfile `review_output' byte column str40 block double shapley_value double shapley_percent ///
    double total_r2 double focal_beta double focal_se int N int clusters using `review_results', replace
foreach column in 2 3 5 6 {
    local focal "HighCCEI_both_high"
    if `column' > 3 local focal "ccei_gap_ij"
    local fe "class"
    local block3 "`characteristics' `gender'"
    local singleton_option ""
    if inlist(`column', 3, 6) {
        local fe "id_fe"
        local block3 "`characteristics'"
        local singleton_option "keepsingletons"
    }
    quietly reghdfe Ihat_ig `focal' M_ccei `block3' `shares', ///
        absorb(`fe') vce(cluster class) `singleton_option'
    assert e(N) == 2560 & e(N_clust) == 64
    scalar review_r2 = e(r2)
    scalar review_beta = _b[`focal']
    scalar review_se = _se[`focal']
    local block1 "`focal'"
    local block2 "M_ccei"
    local block4 "`shares'"
    matrix `coalition_r2' = J(32, 1, 0)
    forvalues mask = 1/31 {
        local rhs ""
        forvalues block = 1/4 {
            if mod(floor(`mask' / 2^(`block' - 1)), 2) local rhs "`rhs' `block`block''"
        }
        if `mask' >= 16 quietly reghdfe Ihat_ig `rhs', absorb(`fe') vce(cluster class) `singleton_option'
        else quietly regress Ihat_ig `rhs', vce(cluster class)
        assert e(N) == 2560
        matrix `coalition_r2'[`mask' + 1, 1] = e(r2)
    }
    assert abs(e(r2) - review_r2) < 1e-10
    assert abs(_b[`focal'] - review_beta) < 1e-10
    assert abs(_se[`focal'] - review_se) < 1e-10
    local label1 "Rationality"
    local label2 "M benchmark"
    local label3 "Individual/Friendship"
    local label4 "Corner/Midpoint shares"
    local label5 "Class FE"
    if inlist(`column', 3, 6) local label5 "Individual FE"
    scalar review_sum = 0
    forvalues block = 1/5 {
        scalar contribution = 0
        forvalues mask = 0/31 {
            if !mod(floor(`mask' / 2^(`block' - 1)), 2) {
                local size = 0
                forvalues other = 1/5 {
                    local size = `size' + mod(floor(`mask' / 2^(`other' - 1)), 2)
                }
                local weight = cond(inlist(`size', 0, 4), 1/5, cond(inlist(`size', 1, 3), 1/20, 1/30))
                scalar increment = `coalition_r2'[`mask' + 1 + 2^(`block' - 1), 1] - `coalition_r2'[`mask' + 1, 1]
                assert increment > -1e-10
                scalar contribution = contribution + `weight' * increment
            }
        }
        scalar review_sum = review_sum + contribution
        post `review_output' (`column') ("`label`block''") ///
            (contribution) (100 * contribution / review_r2) (review_r2) ///
            (review_beta) (review_se) (2560) (64)
    }
    assert abs(review_sum - review_r2) < 1e-10
}
postclose `review_output'
use `review_results', clear
isid column block
bysort column: egen double share_sum = total(shapley_percent)
assert abs(share_sum - 100) < 1e-8
drop share_sum
cap mkdir "results/figure_A7_review"
export delimited using "results/figure_A7_review/table3_shapley.csv", replace
list column block shapley_value shapley_percent total_r2, noobs sepby(column) abbreviate(25)
di as result "SUCCESS: Figure A7; four exact five-block decompositions, N=2560, clusters=64."
log close distance_shapley_review


********************************************************************************
* Leave-one-choice-out validation: six Table 3 specifications, 18 folds.
* Run independently from Code after programs/calculate_indices_disjoint.R.
* A full 18-fold run is required for manuscript copying; no reversed directions.
********************************************************************************
clear
set more off
do "programs/hdfe_cluster_vce.do"
local code_dir `"`c(pwd)'"'
local holdout_dir : environment LOCO_OUTPUT_DIR
if `"`holdout_dir'"' == "" local holdout_dir `"`code_dir'/results/tests/disjoint_choice"'
capture confirm file `"`holdout_dir'/run_config.dta"'
if _rc {
    di as text "Hold-out table not regenerated: run programs/calculate_indices_disjoint.R first."
}
else {
    cap mkdir "Logs"
    capture log close leave_one_choice_out
    log using "Logs/08_leave_one_choice_out.log", name(leave_one_choice_out) text replace
    use `"`holdout_dir'/run_config.dta"', clear
    assert _N == 1 & version == 3 & planned_folds == 18 & inrange(folds, 1, 18)
    assert training_choices == 17 & heldout_choices == 1 & group_choices == 18
    local folds = folds[1]
    local pairs = n_pairs[1]
    local production = (`folds' == 18 & `pairs' == 652)
    forvalues fold = 1/`folds' {
        local suffix : display %02.0f `fold'
        confirm file `"`holdout_dir'/indices/fold_`suffix'.dta"'
    }
    tempfile table3_panel fitted_results
    do "programs/prepare_table3_controls.do"
    keep if balanced_t3
    assert _N == 2512
    egen long loco_class_fe = group(class)
    drop corner_share_i corner_share_diff mid_share_i mid_share_diff
    save `table3_panel'
    local individual "mathscore_i mathscore_diff height_i height_diff outgoing_i outgoing_diff opened_i opened_diff agreeable_i agreeable_diff conscientious_i conscientious_diff stable_i stable_diff"
    local gender "female_i_male_j male_i_female_j"
    local friendship "inclass_n_friends_i inclass_n_diff inclass_popularity_i inclass_pop_diff"
    local missing_controls "mathscore_diff_missing outgoing_diff_missing opened_diff_missing agreeable_diff_missing conscientious_diff_missing stable_diff_missing"
    local shares "corner_share_i corner_share_diff mid_share_i mid_share_diff"
    local full_controls "`individual' `friendship' `missing_controls' `shares'"
    tempname fitted
    postfile `fitted' byte fold byte column str32 term double coefficient double se ///
        double p double n double r2 double clusters double df_r byte omitted using `fitted_results', replace
    forvalues fold = 1/`folds' {
        local suffix : display %02.0f `fold'
        use `table3_panel', clear
        merge 1:1 id post using `"`holdout_dir'/indices/fold_`suffix'.dta"', ///
            keep(master match) assert(match using) nogen
        assert fold == `fold' & n_donors == `pairs'-1
        assert !missing(ccei_train, partner_ccei_train, M_holdout)
        bysort id: egen valid_waves = total(!missing(I_holdout))
        keep if valid_waves == 2
        assert _N > 0
        local sample_n = _N
        gen byte loco_high = (ccei_train >= partner_ccei_train)
        gen double loco_gap = ccei_train-partner_ccei_train
        gen double corner_share_i = corner_share_train
        gen double corner_share_diff = corner_diff_train
        gen double mid_share_i = mid_share_train
        gen double mid_share_diff = mid_diff_train
        local column = 0
        foreach focal in loco_high loco_gap {
            forvalues spec = 1/3 {
                local ++column
                local controls ""
                local fe "class"
                if `spec' > 1 local controls "`full_controls'"
                if `spec' == 2 local controls "`controls' `gender'"
                if `spec' == 3 local fe "id_fe"
                quietly reghdfe I_holdout `focal' M_holdout `controls', ///
                    absorb(`fe') vce(cluster class) keepmata
                hdfe_cluster_vce loco_class_fe
                assert e(N) == `sample_n'
                assert _se[`focal'] > 0 & _se[M_holdout] > 0
                local fitted_terms : colnames e(b)
                foreach term of local fitted_terms {
                    local p = cond(_se[`term'] > 0, 2*ttail(e(df_r), abs(_b[`term']/_se[`term'])), .)
                    post `fitted' (`fold') (`column') ("`term'") ///
                        (_b[`term']) (_se[`term']) (`p') (e(N)) (e(r2)) (e(N_clust)) (e(df_r)) (_se[`term']==0)
                }
            }
        }
        di as text "Hold-out: estimated fold `fold'/`folds'; N=`sample_n'."
    }
    postclose `fitted'
    use `fitted_results', clear
    isid fold column term
    save `"`holdout_dir'/fold_estimates.dta"', replace
    preserve
        keep if inlist(term, "loco_high", "loco_gap")
        bysort column: assert _N == `folds'
        assert !missing(p) & se > 0
        export delimited using `"`holdout_dir'/focal_fit_inference.csv"', replace
        collapse (p50) n r2 clusters (min) n_min=n (max) n_max=n, by(column)
        forvalues column = 1/6 {
            foreach stat in n r2 clusters n_min n_max {
                quietly summarize `stat' if column == `column', meanonly
                local fmt "%9.0fc"
                if "`stat'" == "r2" local fmt "%9.3f"
                if "`stat'" == "clusters" local fmt "%9.1f"
                local `stat'`column' = strtrim(string(r(mean), "`fmt'"))
            }
        }
    restore
    keep if inlist(term, "loco_high", "loco_gap", "M_holdout")
    bysort term column: egen double median = median(coefficient)
    bysort term column: egen double lower = pctile(coefficient), p(2.5)
    bysort term column: egen double upper = pctile(coefficient), p(97.5)
    bysort term column: gen int n_estimates = _N
    bysort term column: keep if _n == 1
    assert n_estimates == `folds'
    keep term column median lower upper n_estimates
    save `"`holdout_dir'/fold_summary.dta"', replace
    local tex_path `"`holdout_dir'/table_leave_one_choice_out_partial.tex"'
    if `production' local tex_path "results/tables/table_leave_one_choice_out.tex"
    local bs = char(92)
    gen str12 median_text = strtrim(string(median, "%9.3f"))
    gen str12 lower_text = strtrim(string(lower, "%9.3f"))
    gen str12 upper_text = strtrim(string(upper, "%9.3f"))
    local label_loco_high "Higher`bs' CCEI_i"
    local label_loco_gap "CCEI_i-CCEI_j"
    local label_M_holdout "M_{ig}"
    tempname holdout_table
    file open `holdout_table' using `"`tex_path'"', write replace
    file write `holdout_table' "`bs'resizebox{`bs'textwidth}{!}{%" _n
    file write `holdout_table' "`bs'begin{tabular}{lcccccc}`bs'toprule" _n
    file write `holdout_table' "& `bs'multicolumn{3}{c}{Higher-CCEI indicator} & `bs'multicolumn{3}{c}{CCEI difference}`bs'`bs'" _n
    file write `holdout_table' "`bs'cmidrule(lr){2-4}`bs'cmidrule(lr){5-7}" _n
    file write `holdout_table' "Held-out distance & (1) & (2) & (3) & (4) & (5) & (6)`bs'`bs'`bs'midrule" _n
    foreach term in loco_high loco_gap M_holdout {
        foreach stat in median_text lower_text upper_text {
            if "`stat'" == "median_text" file write `holdout_table' (char(36)) "`label_`term''" (char(36))
            if "`stat'" == "lower_text" file write `holdout_table' "2.5th fold percentile"
            if "`stat'" == "upper_text" file write `holdout_table' "97.5th fold percentile"
            forvalues column = 1/6 {
                local cell ""
                quietly levelsof `stat' if term == "`term'" & column == `column', local(cell) clean
                file write `holdout_table' " & `cell'"
            }
            file write `holdout_table' "`bs'`bs'" _n
        }
    }
    file write `holdout_table' "`bs'midrule" _n
    foreach stat in n n_min n_max r2 clusters {
        local label = cond("`stat'" == "n", "Median N", cond("`stat'" == "n_min", "Minimum N", cond("`stat'" == "n_max", "Maximum N", cond("`stat'" == "r2", "Median R-squared", "Median class clusters"))))
        file write `holdout_table' "`label'"
        forvalues column = 1/6 {
            file write `holdout_table' " & ``stat'`column''"
        }
        file write `holdout_table' "`bs'`bs'" _n
    }
    file write `holdout_table' "Fixed effects & Class & Class & Individual & Class & Class & Individual`bs'`bs'" _n
    foreach label in "Student/friendship controls" "Training-choice share controls" {
        file write `holdout_table' "`label' & & " (char(36)) "`bs'checkmark" ///
            (char(36)) " & " (char(36)) "`bs'checkmark" (char(36)) " & & " ///
            (char(36)) "`bs'checkmark" (char(36)) " & " (char(36)) ///
            "`bs'checkmark" (char(36)) "`bs'`bs'" _n
    }
    file write `holdout_table' "Folds & `folds' & `folds' & `folds' & `folds' & `folds' & `folds'`bs'`bs'" _n
    file write `holdout_table' "`bs'bottomrule`bs'end{tabular}}" _n
    file close `holdout_table'
    if `production' copy `"`tex_path'"' "../Overleaf/tables_2025/table_leave_one_choice_out.tex", replace
    di as result "SUCCESS: six hold-out specifications in each of `folds' folds; complete individual-fit inference saved."
    log close leave_one_choice_out
}
