function [MME_aggregation_flag, NLLS_metric_flag, parallel_flag] = HPZ_Interface_Optimization_settings(action)   
    % "True" means that the estimation calculation is numeric and "False" means
% analytic estimation
global numeric_flag
% The max number of convergance points MME
global MME_min_counter;
% The max number of convergance points NLLS
global NLLS_min_counter;
% The max number of convergance points BI
global BI_min_counter;
% Time (minutes) that user want to spend on running the code on his machine
global MME_max_time_estimation;
%
global NLLS_max_time_estimation;
%
global BI_max_time_estimation;
      
    %% initialization
    MME_min_counter = 3;
    MME_max_time_estimation = Inf;
    MME_aggregation_flag = 0;

    NLLS_min_counter = 5;
    NLLS_max_time_estimation = Inf;
    NLLS_metric_flag = 0;

    %% initialization
    BI_min_counter = 3;
    BI_max_time_estimation = Inf;
    
    parallel_flag = true;

    if numeric_flag ~= true
        parallel_flag = false;
        parallel_label_ch_val = 0;
        parallel_label_ch_enable = 'off';
    else 
        parallel_flag = true;
        parallel_label_ch_val = 1;
        parallel_label_ch_enable = 'on';
    end
    
    %% NLLS
    if action == 2

        enable_string_NLLS = 'on';
        enable_string_BI = 'off';
        enable_string_MME = 'off';
        MME_min_counter = 0;
        MME_max_time_estimation = 0;
        MME_aggregation_flag =0;
        BI_min_counter = 0;
        BI_max_time_estimation = 0;        

    %% MME
    elseif action == 3

        enable_string_NLLS = 'off';
        enable_string_BI = 'off';
        enable_string_MME = 'on';        
        NLLS_min_counter = 0;
        NLLS_max_time_estimation = 0;
        NLLS_metric_flag = 0;
        BI_min_counter = 0;
        BI_max_time_estimation = 0;         

    %% BI
    elseif action == 4

        enable_string_NLLS = 'off';
        enable_string_BI = 'on';
        enable_string_MME = 'off';        
        NLLS_min_counter = 0;
        NLLS_max_time_estimation = 0;
        NLLS_metric_flag = 0;
        MME_min_counter = 0;
        MME_max_time_estimation = 0;
        MME_aggregation_flag =0;        

    else  
        
        return
        
    end

    % create the gui figure
    sz = [450 470]; % figure size
    screensize = get(0,'ScreenSize');
    xpos = ceil((screensize(3)-sz(2))/2); % center the figure on the
    ypos = ceil((screensize(4)-sz(1))/2); % center the figure on the

    %% Optimization Setting
    S.fh = figure('units','pixels',...
                  'position',[xpos, ypos, sz(2), sz(1)],...
                  'menubar','none',...
                  'name','Optimization Settings',...
                  'numbertitle','off',...
                  'resize','off');

    %% Optimization settings MME
    S.label_MME = uicontrol('style','text',...
                     'units','pix',...
                     'position',[15 420 250 30],...
                     'backgroundc',get(S.fh,'color'),...
                     'fontsize',12,'fontweight','bold',... 
                     'HorizontalAlignment','left',...
                     'string','Money Metric Index Method');

    S.initial_points_MME = uicontrol('style','text',...
                     'enable', enable_string_MME, ...
                     'units','pix',...
                     'position',[15 390 150 40],...
                     'backgroundc',get(S.fh,'color'),...
                     'fontsize',10,...
                     'string','Number of convergence points:');

    S.initial_points_MME_pop = uicontrol('style','pop',...
                      'units','pixels',...
                      'enable', enable_string_MME, ...
                      'position',[170 375 40 40],...
                      'string',{'3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20'});

    S.estimated_time_MME_label = uicontrol('style','text',...
                     'units','pix',...
                     'enable', enable_string_MME, ...
                     'position',[220 390 150 30],...
                     'backgroundc',get(S.fh,'color'),...
                     'fontsize',10,...
                     'string','Allocated time (minutes):');

    S.estimated_time_MME_text = uicontrol('style','edit',...
                     'enable', enable_string_MME, ...
                     'units','pix',...
                     'position',[375 400 80 25],...
                     'backgroundc','white',...
                     'fontsize',10);


    %% Aggregation MME
    S.ed_MME = uicontrol('style','edit',...
                     'unit','pix',...
                     'enable', enable_string_MME, ...
                     'position',[20 360 170 20],...
                     'backgroundc',get(S.fh,'color'),...
                     'string','Aggregation  Method');

    S.bg_MME = uibuttongroup('units','pix',...
                         'pos',[20 320 430 40]);

    S.Aggregation_MME_rd(1) = uicontrol(S.bg_MME,...
                        'enable', enable_string_MME, ...
                        'style','rad',...
                        'unit','pix',...
                        'position',[10 5 160 30],...
                        'string',' Maximum Waste');

    S.Aggregation_MME_rd(2) = uicontrol(S.bg_MME,...
                        'enable', enable_string_MME, ...
                        'style','rad',...
                        'unit','pix',...
                        'position',[145 5 250 30],...
                        'string',' Mean Waste');

    S.Aggregation_MME_rd(3) = uicontrol(S.bg_MME,...
                        'enable', enable_string_MME, ...                    
                        'style','rad',...
                        'value', 1.0,...                        
                        'unit','pix',...
                        'position',[255 5 170 30],...
                        'string',' AVG(SSQ(Wastes))');         
    %% End of MME settings


    %% Optimization settings NLLS
    S.label_NLLS = uicontrol('style','text',...
                     'units','pix',...
                     'position',[15 190 190 30],...
                     'backgroundc',get(S.fh,'color'),...
                     'fontsize',12,'fontweight','bold',... 
                     'string','Nonlinear Least Squares');

    S.initial_points_NLLS = uicontrol('style','text',...
                     'enable', enable_string_NLLS, ...
                     'units','pix',...
                     'position',[15 160 150 40],...
                     'backgroundc',get(S.fh,'color'),...
                     'fontsize',10,...
                     'string','Number of convergence points:');

    S.initial_points_NLLS_pop = uicontrol('style','pop',...
                      'enable', enable_string_NLLS, ...
                      'units','pixels',...
                      'position',[170 145 40 40],...
                      'string',{'5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20'});

    S.estimated_time_NLLS_label = uicontrol('style','text',...
                     'enable', enable_string_NLLS, ...
                     'units','pix',...
                     'position',[220 160 150 30],...
                     'backgroundc',get(S.fh,'color'),...
                     'fontsize',10,...
                     'string','Allocated time (minutes):');

    S.estimated_time_NLLS_text = uicontrol('style','edit',...
                     'units','pix',...
                     'enable', enable_string_NLLS, ...
                     'position',[375 170 80 25],...
                     'backgroundc','white',...
                     'fontsize',10);

    %% Metric Method NLLS
    S.ed_NLLS = uicontrol('style','edit',...
                     'enable', enable_string_NLLS, ...
                     'unit','pix',...
                     'position',[20 130 170 20],...
                     'backgroundc',get(S.fh,'color'),...
                     'string','Metric  Selection');

    S.bg_NLSS = uibuttongroup('units','pix',...
                         'pos',[20 90 430 40]);

    S.metric_NLLS_rd(1) = uicontrol(S.bg_NLSS,...
                        'style','rad',...
                        'enable', enable_string_NLLS, ...
                        'unit','pix',...
                        'position',[40 5 160 30],...
                        'string',' Euclidean metric');

    S.metric_NLLS_rd(2) = uicontrol(S.bg_NLSS,...
                        'style','rad',...
                        'enable', enable_string_NLLS, ...
                        'unit','pix',...
                        'position',[220 5 175 30],...
                        'string',' Choi et al. (2007) metric');
  
    %% Optimization settings BI
    S.label_BI = uicontrol('style','text',...
                     'units','pix',...
                     'position',[10 270 175 30],...
                     'backgroundc',get(S.fh,'color'),...
                     'fontsize',12,'fontweight','bold',... 
                     'string','Binary Index Method');

    S.initial_points_BI = uicontrol('style','text',...
                     'enable', enable_string_BI, ...
                     'units','pix',...
                     'position',[15 240 150 40],...
                     'backgroundc',get(S.fh,'color'),...
                     'fontsize',10,...
                     'string','Number of convergence points:');

    S.initial_points_BI_pop = uicontrol('style','pop',...
                      'units','pixels',...
                      'enable', enable_string_BI, ...
                      'position',[170 225 40 40],...
                      'string',{'3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20'});

    S.estimated_time_BI_label = uicontrol('style','text',...
                     'units','pix',...
                     'enable', enable_string_BI, ...
                     'position',[220 240 150 30],...
                     'backgroundc',get(S.fh,'color'),...
                     'fontsize',10,...
                     'string','Allocated time (minutes):');

    S.estimated_time_BI_text = uicontrol('style','edit',...
                     'enable', enable_string_BI, ...
                     'units','pix',...
                     'position',[375 250 80 25],...
                     'backgroundc','white',...
                     'fontsize',10);
                    
%parallel computing                    
    S.parallel_label = uicontrol('style','text',...
                     'units','pix',...
                     'position',[15 40 150 30],...
                     'backgroundc',get(S.fh,'color'),...
                     'fontsize',12,'fontweight','bold',... 
                     'string','Parallel Processing');
                 
    S.parallel_label_ch = uicontrol('style','check',...
                     'unit','pix',...
                     'position',[175 47 275 25],...
                     'string',' Use matlab parallel computing package.',...
                     'value', parallel_label_ch_val, ...
                     'enable', parallel_label_ch_enable,...
                     'fontsize',10);


    S.pb = uicontrol('style','push',...
                     'unit','pix',...
                     'position',[175 5 100 30],...
                     'string','OK', ...
                     'callback',{@pb_call,S});

    uiwait(S.fh)  % Prevent all other processes from starting until closed.

    pause(0);
    
    %% OK button
    function [] = pb_call(varargin)
        
        % Callback for the popup.
        S = varargin{3};  % Get the structure.

        if strcmpi(get(S.initial_points_NLLS, 'enable'), 'on') % NLLS
            rd_vals_NLLS = get (S.metric_NLLS_rd(:), 'value');
            if rd_vals_NLLS{1} == 1;
                % Euclidean
                NLLS_metric_flag = 1;
            else
                % Choi (2007) metirc
                NLLS_metric_flag = 2;
            end % end switch
            
            % set thte number of convergance points for NLLS
            P_NLLS = get(S.initial_points_NLLS_pop,{'string','val'});  % Get the users choice.
            NLLS_min_counter = str2num(P_NLLS{1}{P_NLLS{2}}); %#ok<*ST2NM>
            
            if strcmp(get(S.estimated_time_NLLS_text,'string'), '')
                NLLS_max_time_estimation = Inf;
            else
                NLLS_max_time_estimation = str2num(get(S.estimated_time_NLLS_text,'string'));
            end

        elseif strcmpi(get(S.initial_points_MME, 'enable'), 'on') % NLLS % MME
            rd_vals_MME = get (S.Aggregation_MME_rd(:), 'value');
            if rd_vals_MME{1} == 1
                    % Max Waste
                    MME_aggregation_flag = 1;

            elseif rd_vals_MME{2} == 1
                    % Mean Waste
                    MME_aggregation_flag = 2;

            else
                    % Sum of Squares Wastes
                    MME_aggregation_flag = 3;
            end % end of switch
            
            % set the number of convergance points MME
            P_MME = get(S.initial_points_MME_pop,{'string','val'});  % Get the users choice.
            MME_min_counter = str2num(P_MME{1}{P_MME{2}});
            
            if strcmp(get(S.estimated_time_MME_text,'string'), '') 
                MME_max_time_estimation = Inf;
            else
                MME_max_time_estimation = str2num(get(S.estimated_time_MME_text,'string'));
            end

        elseif strcmpi(get(S.initial_points_BI, 'enable'), 'on') % NLLS % MME
            
            % set the number of convergance points MME
            P_BI = get(S.initial_points_BI_pop,{'string','val'});  % Get the users choice.
            BI_min_counter = str2num(P_BI{1}{P_BI{2}});
            
            if strcmp(get(S.estimated_time_BI_text,'string'), '') 
                BI_max_time_estimation = Inf;
            else
                BI_max_time_estimation = str2num(get(S.estimated_time_BI_text,'string'));
            end
            
        end % end of if

        if get(S.parallel_label_ch, 'value') == 1.0 % Parallel Computing
            % Use matlabpool
            parallel_flag = true;
        else
            % Use serial version
            parallel_flag = false;
        end
        
        % close the window
        close(S.fh);

    end % end of call back function


end % end of function