suppressPackageStartupMessages({ library(haven); library(ggplot2); library(dplyr); library(grid) })
code_dir <- normalizePath("Code")
# Figure 6: Joint Collective Outcomes
################################################################################

# Saved inputs are generated by 11_collective_quality.do.
# To run this section and its appendix alone, load haven/ggplot2/dplyr and set code_dir.
collective_result_dir <- file.path(code_dir, "results/new_indices/collective_rationality_summary")
joint_data <- read_dta(file.path(collective_result_dir, "analysis_sample.dta"))
stopifnot(nrow(joint_data) == 1304, length(unique(joint_data$group_id)) == 652,
          !anyDuplicated(joint_data[c("group_id", "post")]),
          all(is.finite(as.matrix(joint_data[c("ccei_g", "ceiv_g", "ceiv_at1")]))),
          all(joint_data$ceiv_at1 %in% 0:1),
          all(joint_data$ceiv_g[joint_data$ceiv_at1 == 1] == 1))
joint_category <- 1L + (joint_data$ccei_g >= 1 - 1e-9) + 2L * joint_data$ceiv_at1
stopifnot(all(joint_category == joint_data$joint_category),
          all(joint_data$ceiv_g >= 0 & joint_data$ceiv_g <= 1))
joint_counts <- data.frame(outcome = 1:4, ccei_one = c(0, 1, 0, 1), ceiv_one = c(0, 0, 1, 1),
                     n = tabulate(joint_category, nbins = 4))
joint_counts$share <- joint_counts$n / nrow(joint_data)
joint_ames <- read.csv(file.path(collective_result_dir, "figure6_ame.csv"))
stopifnot(sum(joint_counts$n) == 1304,
          max(abs(joint_ames$share - joint_counts$share[joint_ames$outcome])) < 1e-12)
write.csv(joint_counts, file.path(collective_result_dir, "joint_outcome_counts.csv"), row.names = FALSE)
plot_joint_outcomes <- function(data, counts) {
  # Draw endpoint categories last, without jittering the observed index values.
  points <- data[order(data$joint_category), ]
  points$outcome <- factor(points$joint_category, levels = counts$outcome)
  legend_labels <- sprintf("%s: %s (%.1f%%)",
    c("Both < 1", "CCEI = 1 only", "CEIV = 1 only", "Both = 1"),
    format(counts$n, big.mark = ",", trim = TRUE), 100 * counts$share)
  legend_title <- sprintf("Pair-waves (n = %s)", format(nrow(data), big.mark = ",", trim = TRUE))
  point_fill <- c("grey65", "#D73027", "#2C7BB6", "black")
  point_colour <- c("grey35", "grey15", "grey15", "black")
  point_size <- c(1.8, 2.1, 2.3, 4.5)
  point_alpha <- c(.55, 1, 1, 1)

  ggplot(points, aes(ccei_g, ceiv_g)) +
    annotate("segment", x = 0, y = 0, xend = 1, yend = 1,
             colour = "grey65", linewidth = .5) +
    geom_vline(xintercept = 1, colour = "grey35", linetype = "dashed", linewidth = .5) +
    geom_hline(yintercept = 1, colour = "grey35", linetype = "dashed", linewidth = .5) +
    geom_point(aes(fill = outcome, colour = outcome, shape = outcome,
                   size = outcome, alpha = outcome), stroke = .4) +
    annotate("text", x = .11, y = .14, label = "CEIV = CCEI", angle = 45,
             colour = "grey40", size = 5) +
    scale_fill_manual(name = legend_title, values = point_fill, labels = legend_labels,
                      drop = FALSE) +
    scale_shape_manual(name = legend_title, values = c(21, 21, 23, 22),
                       labels = legend_labels, drop = FALSE) +
    scale_colour_manual(values = point_colour, guide = "none") +
    scale_size_manual(values = point_size, guide = "none") +
    scale_alpha_manual(values = point_alpha, guide = "none") +
    guides(fill = guide_legend(override.aes = list(size = point_size, alpha = point_alpha,
                                                 colour = point_colour))) +
    scale_x_continuous(breaks = seq(0, 1, .2), labels = function(x) sprintf("%.1f", x),
                       limits = c(-.025, 1.025), expand = c(0, 0)) +
    scale_y_continuous(breaks = seq(0, 1, .2), labels = function(x) sprintf("%.1f", x),
                       limits = c(-.025, 1.025), expand = c(0, 0)) +
    coord_fixed() +
    labs(x = "Group CCEI", y = "Group CEIV") +
    theme_minimal(base_size = 17) +
    theme(panel.grid.minor = element_blank(),
          panel.grid.major = element_line(colour = "grey92", linewidth = .7),
          axis.text = element_text(size = 16, colour = "grey30"),
          axis.title = element_text(size = 18),
          axis.title.x = element_text(margin = margin(t = 12)),
          axis.title.y = element_text(margin = margin(r = 12)),
          legend.position = "inside", legend.position.inside = c(.955, .03),
          legend.justification = c(1, 0),
          legend.background = element_rect(fill = "white", colour = "black", linewidth = .5),
          legend.title = element_text(size = 15, margin = margin(b = 6)),
          legend.text = element_text(size = 14),
          legend.key.height = grid::unit(.52, "cm"),
          legend.margin = margin(6, 7, 6, 7),
          plot.background = element_rect(fill = "white", colour = NA),
          plot.margin = margin(12, 12, 12, 12))
}
joint_plot <- plot_joint_outcomes(joint_data, joint_counts)
figure6_file <- file.path(collective_result_dir, "joint_outcome_quadrants.pdf")
ggsave(figure6_file, joint_plot, width = 7, height = 6.3)
print(joint_counts)

draft_figure_dir <- file.path(code_dir, "..", "Overleaf/figures_2025/collective_rationality")
dir.create(draft_figure_dir, recursive = TRUE, showWarnings = FALSE)
stopifnot(file.copy(figure6_file, file.path(draft_figure_dir, basename(figure6_file)),
                   overwrite = TRUE))

################################################################################
# Appendix Figure 6 robustness: exclude all-corner/midpoint collective choices.
# Exact rule and inclusive 2.5-percentage-point payoff-share buffer.
################################################################################
choice_patterns <- bind_rows(lapply(c("base", "end"), function(wave) {
  raw <- read_dta(file.path(code_dir, "data", paste0(wave, "_raw.dta"))) |>
    filter(round_number >= 19, mover == 1, group_id %in% joint_data$group_id)
  stopifnot(all(raw$coord_x + raw$coord_y > 0))
  raw |>
    mutate(post = as.integer(wave == "end"), share = coord_x / (coord_x + coord_y),
           exact = share %in% c(0, .5, 1),
           buffered = share <= .025 | share >= .975 | (share >= .475 & share <= .525)) |>
    group_by(group_id, post) |>
    summarise(n_choices = n(), all_exact = all(exact), all_buffered = all(buffered),
              .groups = "drop")
}))
stopifnot(nrow(choice_patterns) == 1304, all(choice_patterns$n_choices == 18),
          all(!choice_patterns$all_exact | choice_patterns$all_buffered))
exclusion_data <- left_join(joint_data, choice_patterns, by = c("group_id", "post"))
stopifnot(!anyNA(exclusion_data$all_exact), !anyNA(exclusion_data$all_buffered))
appendix_counts <- list()
appendix_plots <- list()
for (rule in c("exact", "buffered")) {
  retained <- exclusion_data[!exclusion_data[[paste0("all_", rule)]], ]
  counts <- data.frame(outcome = 1:4, ccei_one = c(0, 1, 0, 1), ceiv_one = c(0, 0, 1, 1),
                       n = tabulate(retained$joint_category, nbins = 4))
  counts$share <- counts$n / nrow(retained)
  counts$rule <- rule
  counts$retained_n <- nrow(retained)
  counts$excluded_n <- nrow(exclusion_data) - nrow(retained)
  stopifnot(sum(counts$n) == counts$retained_n[1], abs(sum(counts$share) - 1) < 1e-12)
  appendix_counts[[rule]] <- counts
  appendix_plots[[rule]] <- plot_joint_outcomes(retained, counts) +
    labs(title = if (rule == "exact") "(a) Exact corner/midpoint exclusion" else
      "(b) Exclusion with 2.5-point buffer") +
    theme(plot.title = element_text(size = 16))
}
write.csv(bind_rows(appendix_counts), file.path(collective_result_dir, "joint_outcome_exclusion_counts.csv"), row.names = FALSE)
write.csv(choice_patterns, file.path(collective_result_dir, "joint_outcome_exclusion_flags.csv"), row.names = FALSE)
appendix_figure <- cowplot::plot_grid(plotlist = appendix_plots, nrow = 1)
appendix_file <- file.path(collective_result_dir, "joint_outcomes_excluding_simple_choices.png")
ggsave(appendix_file, appendix_figure, width = 13, height = 6.4, dpi = 300, bg = "white")
stopifnot(file.copy(appendix_file, file.path(draft_figure_dir, basename(appendix_file)), overwrite = TRUE))
print(bind_rows(appendix_counts))

################################################################################
# Figure 7: Collective CCEI And CEIV By Members' Individual CCEI Category
################################################################################

# Saved inputs are generated by 11_collective_quality.do.
# To run this section alone, load haven/ggplot2/dplyr/grid and set code_dir to Code.
collective_result_dir <- file.path(code_dir, "results/new_indices/collective_rationality_summary")
category_data <- read_dta(file.path(collective_result_dir, "analysis_sample.dta"))
stopifnot(nrow(category_data) == 1304, !anyDuplicated(category_data[c("group_id", "post")]),
          all(is.finite(as.matrix(category_data[c("ccei_min", "ccei_max", "ccei_g", "ceiv_g")]))))
category_pooled_median <- median(c(category_data$ccei_min, category_data$ccei_max))
stopifnot(!any(c(category_data$ccei_min, category_data$ccei_max) == category_pooled_median),
          max(abs(category_data$pooled_median - category_pooled_median)) < 1e-12,
          all(category_data$pair_category == (category_data$ccei_min > category_pooled_median) +
                                             (category_data$ccei_max > category_pooled_median)))
category_data$pair_category <- factor(category_data$pair_category, levels = 0:2,
                                      labels = c("Low-Low", "Low-High", "High-High"))
draft_figure_dir <- file.path(code_dir, "..", "Overleaf/figures_2025/collective_rationality")
dir.create(draft_figure_dir, recursive = TRUE, showWarnings = FALSE)

for (outcome in c("ccei", "ceiv")) {
  variable <- paste0(outcome, "_g")
  title <- toupper(outcome)
  category_stats <- category_data |>
    group_by(pair_category) |>
    summarise(mean = mean(.data[[variable]]), sd = sd(.data[[variable]]), n = n(),
              se = sd / sqrt(n), ci = qt(.975, n - 1) * se, .groups = "drop")
  write.csv(category_stats, file.path(collective_result_dir, paste0("group_", outcome, "_category_means.csv")), row.names = FALSE)
  category_comparisons <- list(c("Low-Low", "Low-High"), c("Low-High", "High-High"), c("Low-Low", "High-High"))
  category_diffs <- bind_rows(lapply(category_comparisons, function(categories) {
    lower <- category_data[[variable]][category_data$pair_category == categories[1]]
    upper <- category_data[[variable]][category_data$pair_category == categories[2]]
    test <- t.test(lower, upper)
    difference <- mean(upper) - mean(lower)
    p <- test$p.value
    mark <- if (p < .01) "**" else if (p < .05) "*" else if (p < .1) "+" else ""
    data.frame(lower = categories[1], upper = categories[2], difference = difference,
               p = p, label = sprintf("Diff. = %.3f%s", difference, mark))
  }))
  write.csv(category_diffs, file.path(collective_result_dir, paste0("group_", outcome, "_category_differences.csv")), row.names = FALSE)

  category_y_min <- max(.75, floor((min(category_stats$mean - category_stats$ci) - .02) * 100) / 100)
  category_y_top <- max(category_stats$mean + category_stats$ci)
  category_bracket_low <- category_y_top + .025
  category_bracket_high <- category_y_top + .070
  bar <- ggplot(category_stats, aes(pair_category, mean, fill = pair_category)) +
    geom_col(width = .62, colour = "black", linewidth = .3) +
    geom_errorbar(aes(ymin = mean - ci, ymax = mean + ci), width = .16, linewidth = .45) +
    scale_fill_manual(values = c("Low-Low" = "#E39695", "Low-High" = "#D8C98C", "High-High" = "#74A9CF")) +
    scale_x_discrete(labels = c("Low-Low" = "Low\nLow", "Low-High" = "Low\nHigh", "High-High" = "High\nHigh")) +
    scale_y_continuous(breaks = seq(.85, 1, .05), labels = scales::label_number(accuracy = .01), expand = c(0, 0)) +
    coord_cartesian(ylim = c(category_y_min, category_bracket_high + .035)) +
    labs(x = NULL, y = paste("Mean Collective", title)) +
    theme_classic(base_size = 16) +
    theme(legend.position = "none", panel.grid.major = element_line(colour = "grey90", linewidth = .4),
          plot.margin = margin(12, 12, 12, 12), plot.background = element_rect(fill = "white", colour = NA))
  for (i in 1:3) {
    x1 <- c(1, 2, 1)[i]
    x2 <- c(2, 3, 3)[i]
    y <- if (i == 3) category_bracket_high else category_bracket_low
    bar <- bar +
      annotate("segment", x = x1, xend = x2, y = y, yend = y) +
      annotate("segment", x = x1, xend = x1, y = y - .020, yend = y) +
      annotate("segment", x = x2, xend = x2, y = y - .020, yend = y) +
      annotate("label", x = mean(c(x1, x2)), y = y + .012,
               label = category_diffs$label[i], size = 4.2, fill = "white")
  }
  cdf <- ggplot(category_data, aes(.data[[variable]], colour = pair_category, linetype = pair_category)) +
    stat_ecdf(geom = "step", linewidth = .9, pad = FALSE) +
    scale_colour_manual(values = c("Low-Low" = "red", "Low-High" = "grey45", "High-High" = "blue")) +
    scale_linetype_manual(values = c("Low-Low" = "dashed", "Low-High" = "dotdash", "High-High" = "solid")) +
    scale_x_continuous(breaks = seq(0, 1, .2), expand = c(0, 0)) +
    scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, .2), expand = c(0, 0)) +
    coord_cartesian(xlim = c(0, 1)) +
    labs(x = paste("Collective", title), y = "Cumulative probability", colour = NULL, linetype = NULL) +
    theme_minimal(base_size = 16) +
    theme(legend.position = "inside", legend.position.inside = c(.02, .98),
          legend.justification = c("left", "top"),
          legend.background = element_rect(fill = "white", colour = "black"),
          panel.grid.minor = element_blank(), plot.margin = margin(12, 18, 12, 12),
          plot.background = element_rect(fill = "white", colour = NA))

  for (kind in c("bar", "cdf")) {
    plot <- if (kind == "bar") bar else cdf
    plot <- plot + theme(text = element_text(size = 16))
    ggsave(file.path(collective_result_dir, paste0("group_", outcome, "_", kind, ".pdf")), plot,
           width = 5, height = 4.5)
  }

  png(file.path(collective_result_dir, paste0("group_", outcome, "_by_member_ccei_category.png")), width = 3600, height = 2100, res = 300)
  grid.newpage()
  pushViewport(viewport(layout = grid.layout(4, 2, heights = unit(c(.10, .75, .06, .09), "npc"))))
  grid.text(paste("Collective", title, "by members' individual CCEI category"), gp = gpar(fontsize = 20, fontface = "bold"),
            vp = viewport(layout.pos.row = 1, layout.pos.col = 1:2))
  print(bar, newpage = FALSE, vp = viewport(layout.pos.row = 2, layout.pos.col = 1))
  print(cdf, newpage = FALSE, vp = viewport(layout.pos.row = 2, layout.pos.col = 2))
  grid.text(paste("(a) Mean Collective", title), gp = gpar(fontsize = 15),
            vp = viewport(layout.pos.row = 3, layout.pos.col = 1))
  grid.text(paste("(b) CDF of Collective", title), gp = gpar(fontsize = 15),
            vp = viewport(layout.pos.row = 3, layout.pos.col = 2))
  grid.text(sprintf("High: individual CCEI above pooled median %.7f across both waves. N = 1,304 pair-waves.\nLow-Low / Low-High / High-High: %s. 95%% t intervals; Welch tests. + p < .10, * p < .05, ** p < .01.",
                    category_pooled_median, paste(category_stats$n, collapse = " / ")),
            gp = gpar(fontsize = 11, col = "grey30"),
            vp = viewport(layout.pos.row = 4, layout.pos.col = 1:2))
  popViewport()
  dev.off()
  print(category_stats)
  print(category_diffs)
  panel_files <- file.path(collective_result_dir, paste0("group_", outcome, "_", c("bar", "cdf"), ".pdf"))
  stopifnot(file.copy(panel_files, file.path(draft_figure_dir, basename(panel_files)), overwrite = TRUE))
}
cat("Pooled individual CCEI median:", category_pooled_median, "\n")

################################################################################
# Figure 8: Individual Rationality And Joint Collective Outcomes
################################################################################

# Saved inputs are generated by 11_collective_quality.do; figure6 filenames are legacy names.
# To run this section alone, load ggplot2 and set code_dir to the Code folder.
# The same plotter supports the saved risk-aversion and communication splits.
plot_cei_ame <- function(input, output_dir, classification = "original", portrait = FALSE) {
  stopifnot(classification %in% c("original", "a", "b"))
  n_categories <- if (classification == "b") 3L else 4L
  prefix <- if (classification == "original") "cei" else paste0("figure6_", classification)
  d <- read.csv(input)
  split_sample <- "ra_high" %in% names(d)
  communication_split <- all(c("moderator", "group") %in% names(d))
  split_fields <- if (communication_split) c("moderator", "group") else if (split_sample) "ra_high" else character()
  panels <- if (length(split_fields)) unique(d[split_fields]) else data.frame(panel = 1)
  keys <- c(split_fields, "outcome", "member")
  sum_groups <- if (length(split_fields)) do.call(interaction, c(d[c(split_fields, "member")], list(drop = TRUE))) else d$member
  stopifnot(nrow(d) == 2 * n_categories * nrow(panels), !anyDuplicated(d[keys]),
            all(is.finite(as.matrix(d[c("estimate", "low", "high")]))),
            all(abs(tapply(d$estimate, sum_groups, sum)) < 1e-8))
  d[c("estimate", "low", "high")] <- 100 * d[c("estimate", "low", "high")]
  d$outcome <- factor(d$outcome, levels = n_categories:1)
  outcome_labels <- c("1" = "CCEI < 1\nCEI < 1", "2" = "CCEI = 1\nCEI < 1",
                      "3" = "CCEI < 1\nCEI = 1", "4" = "CCEI = 1\nCEI = 1")

  if (classification == "a") {
    outcome_labels <- c("1" = "CCEI < 1\nCEIV < 1", "2" = "CCEI = 1\nCEIV < 1",
                        "3" = "CCEI < 1\nCEIV = 1", "4" = "CCEI = 1\nCEIV = 1")
  }
  if (classification == "b") {
    outcome_labels <- c("1" = "CEIV < 1\nCEIC < 1", "2" = "CEIV = 1\nCEIC < 1",
                        "3" = "CEIV = 1\nCEIC = 1")
  }
  # Use a common axis across split samples, expanding only when their intervals require it.
  limits <- c(-20, 30)
  if (length(split_fields)) limits <- c(min(-20, floor(min(d$low) / 10) * 10),
                               max(30, ceiling(max(d$high) / 10) * 10))
  stopifnot(all(d$low >= limits[1]), all(d$high <= limits[2]))

  # Match 07_Figures_Main.R: base size 14, white background, blue/red members,
  # no redundant legend; titles, panel captions, and notes belong in LaTeX.
  paper_theme <- theme_minimal(base_size = 14) +
    theme(panel.grid.minor = element_blank(),
          panel.grid.major.y = element_blank(),
          plot.background = element_rect(fill = "white", colour = NA),
          axis.text.y = element_text(colour = "black"),
          axis.title.x = element_text(margin = margin(t = 8)),
          plot.margin = margin(8, 12, 6, 6))
  member_colours <- c(maximum = "blue", minimum = "red")
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  output_files <- character()
  for (panel in seq_len(nrow(panels))) {
    keep <- rep(TRUE, nrow(d))
    for (field in split_fields) keep <- keep & d[[field]] == panels[[field]][panel]
    sample <- d[keep, ]
    sample_prefix <- if (communication_split) paste(prefix, panels$moderator[panel], panels$group[panel], sep = "_") else
      if (split_sample) paste0(prefix, "_", c("similar", "different")[panels$ra_high[panel] + 1]) else prefix
    for (member in names(member_colours)) {
      p <- ggplot(sample[sample$member == member, ], aes(estimate, outcome)) +
        geom_vline(xintercept = 0, colour = "grey55", linewidth = 0.35) +
        geom_errorbar(aes(xmin = low, xmax = high), orientation = "y",
                      width = 0.12, linewidth = 0.55, colour = "grey35") +
        geom_point(size = 3, colour = member_colours[member]) +
        scale_x_continuous(limits = limits, breaks = seq(limits[1], limits[2], 10)) +
        scale_y_discrete(labels = outcome_labels, expand = expansion(add = 0.55)) +
        labs(x = "Average marginal effect (percentage points)", y = NULL) +
        paper_theme
      output_file <- file.path(output_dir, paste0(sample_prefix, "_ame_", member, ".png"))
      ggsave(output_file, p,
             width = if (portrait) 5.5 else 6, height = if (portrait) 3 else 5, dpi = 300)
      output_files <- c(output_files, output_file)
    }
  }
  invisible(output_files)
}

collective_result_dir <- file.path(code_dir, "results/new_indices/collective_rationality_summary")
ame_files <- plot_cei_ame(file.path(collective_result_dir, "figure6_ame.csv"),
                          collective_result_dir, classification = "a", portrait = TRUE)
draft_figure_dir <- file.path(code_dir, "..", "Overleaf/figures_2025/collective_rationality")
dir.create(draft_figure_dir, recursive = TRUE, showWarnings = FALSE)
stopifnot(file.copy(ame_files, file.path(draft_figure_dir, basename(ame_files)), overwrite = TRUE))

message("07_Figures_Main.R completed. Outputs: ", file.path(code_dir, "results"))
