********************************************************************************
* 06_Tables_Main.do: Main-paper tables and supplementary CEI/CCEI specifications
* Last updated: 2026-10-10
* Original analysis authors: Byunghun Hahn and Minseon Park
*   Attribution follows the archived table and regression script headers.
*
* Run from Code. All paths below are relative to that directory.
* Locked draft order: Table 1 (summary), Table 2 (balance), Table 3 (distance).
*
* Inputs (data/):
*   panel_individual.dta, panel_group.dta, panel_final.dta
*   panel_group_new_indices.dta (CEIV; built by 11_collective_quality.do)
*   base_raw.dta, end_raw.dta, riskpreference_pre.dta
*   male.dta, height.dta, network_survey.dta
*   Cognitive_raw_pre_full.xlsx, NonCognitive_raw_pre.xlsx
* Tables 1 and 3 benchmark input (generated by IminusM_review/02_ccei_ra_analysis.do):
*   IminusM_review/outputs/data/ccei_ra_candidate_analysis.dta
*
* Called code:
*   programs/prepare_table3_controls.do (exact-choice controls and balanced-subsample flag)
*   programs/prepare_collective_sample.do
*
* Outputs (results/tables/; existing files are replaced):
*   table_ccei_summary_IminusM.tex (Table 1 uses Ihat_ig - M_ccei)
*   table_attrition_balance.tex, table_bargainingCCEI_M.tex (current Table 3)
*   final_collective_ccei.tex, final_collective_ccei_high_low.tex
*   {ccei_g,cei_g,type_a,type_b,type_c}_on_individual_ccei.tex
*   cei_four_outcomes_combined.tex
*   cei_ccei_models_{min,dist}.tex, cei_ccei_ols_min.tex
*   cei_joint_mlogit_{min,dist}.tex
*
* Manuscript copy:
*   ../Overleaf/tables_2025/table_ccei_summary_IminusM.tex
*   ../Overleaf/tables_2025/table_attrition_balance.tex
*   ../Overleaf/tables_2025/table_bargainingCCEI_M.tex
* Table 3 log: Logs/06_table3.log. Its section can run independently from Code.
*
* Other outputs (results/):
*   cei_classification_frequencies.csv, cei_joint_ame_pooled.csv
********************************************************************************

clear all
set more off
set matsize 8000

local distance_var "Ihat_ig"

local code_dir `"`c(pwd)'"'

local replication_dir `"`code_dir'"'
local data_dir `"`replication_dir'/data"'
local tex_dir `"`code_dir'/results/tables"'
cap mkdir `"`code_dir'/results"'
cap mkdir `"`tex_dir'"'

foreach required in panel_individual.dta panel_group.dta panel_final.dta ///
    panel_group_new_indices.dta ///
    base_raw.dta end_raw.dta riskpreference_pre.dta male.dta height.dta ///
    Cognitive_raw_pre_full.xlsx NonCognitive_raw_pre.xlsx network_survey.dta {
    capture confirm file `"`data_dir'/`required'"'
    if _rc {
        di as error "Missing required input: `data_dir'/`required'"
        exit 601
    }
}

********************************************************************************
* Table 1: Summary statistics, with placebo-adjusted preference distance I - M
********************************************************************************

use `"`data_dir'/panel_individual.dta"', clear
merge 1:1 id post using ///
    `"`code_dir'/IminusM_review/outputs/data/ccei_ra_candidate_analysis.dta"', ///
    keepusing(M_ccei n_ccei_donors) assert(match) nogen
assert n_ccei_donors == 651
gen double table1_distance = Ihat_ig - M_ccei

foreach period in 0 1 {
    local suffix = cond(`period' == 0, "base", "end")
    foreach var in ccei_i RA_i {
        quietly summarize `var' if post == `period', detail
        local `var'_`suffix'_mean = r(mean)
        local `var'_`suffix'_sd   = r(sd)
        local `var'_`suffix'_p10  = r(p10)
        local `var'_`suffix'_p50  = r(p50)
        local `var'_`suffix'_p90  = r(p90)
        local `var'_`suffix'_N    = r(N)
    }
    quietly summarize table1_distance if post == `period', detail
    local distance_`suffix'_mean = r(mean)
    local distance_`suffix'_sd   = r(sd)
    local distance_`suffix'_p10  = r(p10)
    local distance_`suffix'_p50  = r(p50)
    local distance_`suffix'_p90  = r(p90)
    local distance_`suffix'_N    = r(N)
    foreach stat in mean sd p10 p50 p90 {
        if abs(`distance_`suffix'_`stat'') < .0005 {
            local distance_`suffix'_`stat' = 0
        }
    }
}

use `"`data_dir'/panel_group.dta"', clear
merge 1:1 group_id post using `"`data_dir'/panel_group_new_indices.dta"', ///
    keepusing(ceiv_g) assert(match) nogen
assert inrange(ceiv_g, 0, 1)

foreach period in 0 1 {
    local suffix = cond(`period' == 0, "base", "end")
    foreach var in ccei_g ceiv_g RA_g {
        quietly summarize `var' if post == `period', detail
        local `var'_`suffix'_mean = r(mean)
        local `var'_`suffix'_sd   = r(sd)
        local `var'_`suffix'_p10  = r(p10)
        local `var'_`suffix'_p50  = r(p50)
        local `var'_`suffix'_p90  = r(p90)
        local `var'_`suffix'_N    = r(N)
    }
}

capture file close summary_file
file open summary_file using `"`tex_dir'/table_ccei_summary_IminusM.tex"', write replace
local bs = char(92)
local distance_tex "`bs'ensuremath{I_{ig}-M_{ig}}"
file write summary_file "& (1) & (2) & (3) & (4) & (5) & (6) `bs'`bs'" _n
file write summary_file " & Mean & SD & p10 & p50 & p90 & N `bs'`bs'" _n
file write summary_file "`bs'midrule" _n
file write summary_file "`bs'multicolumn{7}{l}{`bs'emph{Panel A: Baseline}} `bs'`bs'" _n
file write summary_file "`bs'hspace{1em}Individual CCEI & " %6.3f (`ccei_i_base_mean') " & " %6.3f (`ccei_i_base_sd') " & " %6.3f (`ccei_i_base_p10') " & " %6.3f (`ccei_i_base_p50') " & " %6.3f (`ccei_i_base_p90') " & " %9.0fc (`ccei_i_base_N') " `bs'`bs'" _n
file write summary_file "`bs'hspace{1em}Group CCEI & " %6.3f (`ccei_g_base_mean') " & " %6.3f (`ccei_g_base_sd') " & " %6.3f (`ccei_g_base_p10') " & " %6.3f (`ccei_g_base_p50') " & " %6.3f (`ccei_g_base_p90') " & " %9.0fc (`ccei_g_base_N') " `bs'`bs'" _n
file write summary_file "`bs'hspace{1em}Group CEIV & " %6.3f (`ceiv_g_base_mean') " & " %6.3f (`ceiv_g_base_sd') " & " %6.3f (`ceiv_g_base_p10') " & " %6.3f (`ceiv_g_base_p50') " & " %6.3f (`ceiv_g_base_p90') " & " %9.0fc (`ceiv_g_base_N') " `bs'`bs'" _n
file write summary_file "`bs'hspace{1em}Preference distance `distance_tex' & " %6.3f (`distance_base_mean') " & " %6.3f (`distance_base_sd') " & " %6.3f (`distance_base_p10') " & " %6.3f (`distance_base_p50') " & " %6.3f (`distance_base_p90') " & " %9.0fc (`distance_base_N') " `bs'`bs'" _n
file write summary_file "`bs'hspace{1em}Individual risk aversion & " %6.3f (`RA_i_base_mean') " & " %6.3f (`RA_i_base_sd') " & " %6.3f (`RA_i_base_p10') " & " %6.3f (`RA_i_base_p50') " & " %6.3f (`RA_i_base_p90') " & " %9.0fc (`RA_i_base_N') " `bs'`bs'" _n
file write summary_file "`bs'hspace{1em}Group risk aversion & " %6.3f (`RA_g_base_mean') " & " %6.3f (`RA_g_base_sd') " & " %6.3f (`RA_g_base_p10') " & " %6.3f (`RA_g_base_p50') " & " %6.3f (`RA_g_base_p90') " & " %9.0fc (`RA_g_base_N') " `bs'`bs'" _n
file write summary_file "`bs'addlinespace" _n
file write summary_file "`bs'multicolumn{7}{l}{`bs'emph{Panel B: Endline}} `bs'`bs'" _n
file write summary_file "`bs'hspace{1em}Individual CCEI & " %6.3f (`ccei_i_end_mean') " & " %6.3f (`ccei_i_end_sd') " & " %6.3f (`ccei_i_end_p10') " & " %6.3f (`ccei_i_end_p50') " & " %6.3f (`ccei_i_end_p90') " & " %9.0fc (`ccei_i_end_N') " `bs'`bs'" _n
file write summary_file "`bs'hspace{1em}Group CCEI & " %6.3f (`ccei_g_end_mean') " & " %6.3f (`ccei_g_end_sd') " & " %6.3f (`ccei_g_end_p10') " & " %6.3f (`ccei_g_end_p50') " & " %6.3f (`ccei_g_end_p90') " & " %9.0fc (`ccei_g_end_N') " `bs'`bs'" _n
file write summary_file "`bs'hspace{1em}Group CEIV & " %6.3f (`ceiv_g_end_mean') " & " %6.3f (`ceiv_g_end_sd') " & " %6.3f (`ceiv_g_end_p10') " & " %6.3f (`ceiv_g_end_p50') " & " %6.3f (`ceiv_g_end_p90') " & " %9.0fc (`ceiv_g_end_N') " `bs'`bs'" _n
file write summary_file "`bs'hspace{1em}Preference distance `distance_tex' & " %6.3f (`distance_end_mean') " & " %6.3f (`distance_end_sd') " & " %6.3f (`distance_end_p10') " & " %6.3f (`distance_end_p50') " & " %6.3f (`distance_end_p90') " & " %9.0fc (`distance_end_N') " `bs'`bs'" _n
file write summary_file "`bs'hspace{1em}Individual risk aversion & " %6.3f (`RA_i_end_mean') " & " %6.3f (`RA_i_end_sd') " & " %6.3f (`RA_i_end_p10') " & " %6.3f (`RA_i_end_p50') " & " %6.3f (`RA_i_end_p90') " & " %9.0fc (`RA_i_end_N') " `bs'`bs'" _n
file write summary_file "`bs'hspace{1em}Group risk aversion & " %6.3f (`RA_g_end_mean') " & " %6.3f (`RA_g_end_sd') " & " %6.3f (`RA_g_end_p10') " & " %6.3f (`RA_g_end_p50') " & " %6.3f (`RA_g_end_p90') " & " %9.0fc (`RA_g_end_N') " `bs'`bs'" _n
file write summary_file "`bs'bottomrule" _n
file close summary_file
copy `"`tex_dir'/table_ccei_summary_IminusM.tex"' ///
    `"`code_dir'/../Overleaf/tables_2025/table_ccei_summary_IminusM.tex"', replace

********************************************************************************

* Collective-outcomes appendix table: Low--High is the omitted category.
* Run independently from Code after 11_collective_quality.do.
local code_dir `"`c(pwd)'"'
local collective_dir "results/new_indices/collective_rationality_summary"
local tex_dir "results/tables"
tempfile collective_diagnostics
import delimited using "`collective_dir'/table5_diagnostics.csv", clear asdouble
keep if inrange(column, 1, 3)
isid outcome column
assert _N == 6 & n == 1304 & clusters == 64 & !missing(r2)
save `collective_diagnostics'
import delimited using "`collective_dir'/table5_coefficients.csv", clear asdouble
keep if inrange(column, 1, 3)
isid outcome column term
assert _N == 12 & inlist(outcome, "ccei", "ceiv")
assert inlist(term, "low_low", "high_high")
assert !missing(estimate, se, p) & se > 0 & inrange(p, 0, 1)
merge m:1 outcome column using `collective_diagnostics', assert(match) nogen
local bs = char(92)
gen str40 b_text = strtrim(string(estimate, "%9.3f")) + "`bs'textsuperscript{" + ///
    cond(p < .01, "**", cond(p < .05, "*", cond(p < .1, "+", ""))) + "}"
gen str14 se_text = "(" + strtrim(string(se, "%9.3f")) + ")"
gen str12 n_text = strtrim(string(n, "%9.0fc"))
gen str12 r2_text = strtrim(string(r2, "%9.3f"))
tempname category_table
file open `category_table' using "`tex_dir'/collective_ccei_ceiv_categories.tex", write replace
file write `category_table' "`bs'begin{tabular}{lccc}`bs'toprule" _n
file write `category_table' "& `bs'multicolumn{3}{c}{Individual CCEI category dummies}`bs'`bs'" _n
file write `category_table' "`bs'cmidrule(lr){2-4}" _n "& (1) & (2) & (3)`bs'`bs'`bs'midrule" _n
foreach outcome in ccei ceiv {
    local panel = cond("`outcome'" == "ccei", "A: Group CCEI", "B: Group CEIV")
    file write `category_table' "`bs'multicolumn{4}{l}{`bs'textit{Panel `panel'}}`bs'`bs'[3pt]" _n
    foreach term in low_low high_high {
        local label = cond("`term'" == "low_low", "Low--Low pair", "High--High pair")
        foreach stat in b_text se_text {
            local row_label = cond("`stat'" == "b_text", "`label'", "")
            file write `category_table' "`row_label'"
            forvalues column = 1/3 {
                quietly levelsof `stat' if outcome == "`outcome'" & column == `column' & term == "`term'", local(cell) clean
                file write `category_table' " & `cell'"
            }
            file write `category_table' "`bs'`bs'" _n
        }
    }
    foreach stat in n_text r2_text {
        local label = cond("`stat'" == "n_text", "Observations", "R-squared")
        file write `category_table' "`label'"
        forvalues column = 1/3 {
            quietly levelsof `stat' if outcome == "`outcome'" & column == `column' & term == "high_high", local(cell) clean
            file write `category_table' " & `cell'"
        }
        file write `category_table' "`bs'`bs'" _n
    }
    file write `category_table' "`bs'midrule" _n
}
file write `category_table' "Fixed effects & Class & Class & Pair`bs'`bs'" _n
file write `category_table' "Student and friendship controls &  & " (char(36)) "`bs'checkmark" ///
    (char(36)) " & " (char(36)) "`bs'checkmark" (char(36)) "`bs'`bs'" _n
file write `category_table' "Corner/midpoint share controls &  & " (char(36)) "`bs'checkmark" ///
    (char(36)) " & " (char(36)) "`bs'checkmark" (char(36)) "`bs'`bs'" _n
file write `category_table' "`bs'bottomrule`bs'end{tabular}" _n
file close `category_table'
copy "`tex_dir'/collective_ccei_ceiv_categories.tex" "../Overleaf/tables_2025/collective_ccei_ceiv_categories.tex", replace
di as result "SUCCESS: exported collective-outcomes appendix table with Low--High omitted."


********************************************************************************

di as result "SUCCESS: CEIV manuscript tables refreshed."
